const E=require('../src/script'),R=E.R,fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),vm=require('vm');
const ctx=vm.createContext({});for(const n of ['data','craft118','racing']){let code=fs.readFileSync(path.join(__dirname,'../src/'+n+'.js'),'utf8');if(n==='racing')code=code.replace('const straight=straightSupport(s);','const straight={effective:s.speed};');vm.runInContext(code,ctx);}const legacy=ctx.KM_RACING;
const builds={focus:{speed:100,accel:35,power:35},balanced:{speed:70,accel:50,power:50},highFocus:{speed:100,accel:60,power:60},highBalanced:{speed:80,accel:70,power:70}};
const report={note:'同じ機材・スキルなし・同じ能力合計の組で比較。旧速度式側にも周回修正を適用して速度式の影響を分離。固定AIの結果であり手動の勝率ではない。',rows:[],summary:[],finishedWithin3:0};
for(const [rule,engine]of [['旧速度式＋周回修正',legacy],['V120',R]])for(const [name,stats]of Object.entries(builds))for(const wind of [0,8])for(const course of [1,6]){
 const s=E.newState(501),p=E.character(s,'比較選手'),c=E.createCareer(s,p);c.stage=4;E.startSeries(s);E.prepareRace(s);const r=c.series.race;r.env={weather:wind?'雨':'晴れ',wind:wind?'横風':'無風',windSpeed:wind};r.startPolicy='attack';r.controlMode='manual';const me=r.runners.find(n=>n.isPlayer),gear=E.clone(me.equipment);
 r.runners.forEach(n=>{Object.assign(n.stats,{speed:70,turn:60,start:60,accel:50,power:50},n.isPlayer?stats:{});n.skills=[];n.mastery={};n.equipment=E.clone(gear);delete n.racePersona;delete n.castRole;delete n.castId;});const swapped=r.runners.find(n=>n.course===course);swapped.course=me.course;me.course=course;
 const d=engine.create(r,40120,{keepCourses:true});d.paused=false;const physical=d.boats.map(b=>b.progress),previous=d.boats.map(b=>engine.project(b.x,b.z).s),done=new Set();
 while(!d.finished){engine.tick(d,r,{},engine.DT,true);d.boats.forEach((b,i)=>{const next=engine.project(b.x,b.z).s;if(!done.has(i)){physical[i]+=engine.mod(next-previous[i]+300,600)-300;if(b.finishTime!==null){assert.ok(physical[i]>=1796.4&&physical[i]<=1801,JSON.stringify({rule,name,wind,course,boat:i,physical:physical[i]}));done.add(i);if(rule==='V120')report.finishedWithin3++;}}previous[i]=next;});}
 const b=engine.own(d);assert.ok(engine.valid(d,r));report.rows.push({rule,name,wind,course,total:E.D.statKeys.reduce((v,k)=>v+b.stats[k],0),place:engine.place(d,b),time:b.finishTime,contact:b.metrics.contacts,boundary:b.metrics.boundaries,start:b.startTime});
}
for(const rule of ['旧速度式＋周回修正','V120'])for(const name of Object.keys(builds)){const rows=report.rows.filter(x=>x.rule===rule&&x.name===name),finished=rows.filter(x=>x.time!==null);report.summary.push({rule,name,finished:finished.length,meanTime:finished.reduce((v,x)=>v+x.time,0)/finished.length,meanPlace:rows.reduce((v,x)=>v+x.place,0)/rows.length});}
assert.equal(report.rows.length,32);assert.ok(report.finishedWithin3>70);
fs.writeFileSync(path.join(__dirname,'balance-v120.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({races:report.rows.length,finishedWithin3:report.finishedWithin3,summary:report.summary}));
