'use strict';
const path=require('path'),fs=require('fs'),assert=require('node:assert/strict'),E=require('../script');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');const root=path.resolve(__dirname,'..'),results=[],errors=[];
function fixture(){const s=E.newState(49);E.createCareer(s,E.character(s,'水城 遥'));const c=s.career;c.stage=6;E.startSeries(s);E.prepareRace(s);s.settings.presentation='off';s.settings.haptics=false;return s;}
function requestFixture(type='gift'){const s=fixture(),c=s.career,h=c.bonds.heroines.akari;Object.assign(h,{met:true,metStage:6,metRace:0,step:1,choices:[0],trust:14,affection:30});c.player.money=150;for(let seed=1;seed<10000;seed++){c.affinity.seed=seed;c.affinity.rolled=[];c.affinity.requests=[];if(E.Affinity.afterChapter(c,'akari')?.type===type)break;}return s;}
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.KM_TEST_BROWSER||'/tmp/v105-browser/chrome-headless-shell-linux64/chrome-headless-shell',env:{...process.env,FONTCONFIG_FILE:'/tmp/v105-fonts.conf'},args:['--no-sandbox']});let ctx,page;
async function run(name,fn){try{await fn();results.push({name,passed:true});console.log('PASS',name);}catch(e){results.push({name,passed:false,error:e.stack});console.error('FAIL',name,e.message);}}
async function fresh(s=fixture(),file='index.html',width=390,height=844){if(ctx)await ctx.close();ctx=await browser.newContext({viewport:{width,height},deviceScaleFactor:1,isMobile:true,hasTouch:true});page=await ctx.newPage();page.setDefaultTimeout(8000);page.on('pageerror',e=>errors.push(String(e)));await page.addInitScript(s=>{if(!localStorage.getItem('kyotei_monogatari_v80'))localStorage.setItem('kyotei_monogatari_v80',JSON.stringify(s));},s);await page.goto('file://'+path.join(root,file));await page.waitForFunction(()=>!!window.KM_APP);}
const tap=async(a,v)=>page.locator('[data-action="'+a+'"]'+(v!==undefined?'[data-value="'+v+'"]':'')).first().tap();
const fit=async()=>assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
async function last(action){for(let i=0;i<50;i++){if(await page.locator('[data-action="'+action+'"]').count())return;await tap('novelNext');}throw Error('no choices');}
await run('390px ライバル好感度と広い特訓ボタンを表示 枠消費と加算',async()=>{await fresh();await tap('resume');await fit();assert.match(await page.locator('.affinity-meter').innerText(),/あと35/);const key=await page.evaluate(()=>KM_ENGINE.Development.rival(KM_APP.getState().career).key);await tap('jointTrain','rival|'+key);assert.equal(await page.evaluate(()=>KM_APP.getState().career.affinity.rival),30);assert.match(await page.locator('#app').innerText(),/好感度/);await page.screenshot({path:path.join(root,'previews/v108-affinity-training.png'),fullPage:true});});
await run('師匠は好感度不足で最終話を開けず現在値と不足分を表示',async()=>{const s=fixture(),c=s.career,m=c.cast.mentor.id;for(let i=0;i<4;i++){c.stage=c.series.stage=E.Cast.routes[m].chapters[i].stage;c.stats.races=E.Cast.routeState(c).nextAt;const sc=E.Cast.routeOpen(c);E.chooseMentor(c,sc.key,sc.choices.findIndex(x=>x.aligned));}c.stage=c.series.stage=8;c.stats.races=E.Cast.routeState(c).nextAt;c.affinity.mentors[m]=59;await fresh(s);await tap('resume');await tap('bonds');await tap('mentor');assert.match(await page.locator('#app').innerText(),/好感度あと1/);assert.equal(await page.locator('[data-action="mentorMeet"]').isDisabled(),true);await fit();await page.screenshot({path:path.join(root,'previews/v108-affinity-mentor.png'),fullPage:true});});
await run('ヒロインは好感度ゲージと第7話の不足条件 回復用の訪問を残す',async()=>{const s=fixture(),c=s.career;c.stats.races=40;Object.assign(c.bonds.heroines.mizuki,{met:true,metStage:4,metRace:20,step:6,choices:Array(6).fill(0),trust:90,affection:69});await fresh(s,'index.html',360,740);await tap('resume');await tap('bonds');assert.match(await page.locator('.bond-card').innerText(),/最終話まで 好感度あと1/);assert.equal(await page.locator('[data-action="meet"][data-value="mizuki"]').isDisabled(),false);await fit();await page.screenshot({path:path.join(root,'previews/v108-affinity-heroine.png'),fullPage:true});});
await run('おねだりが自動表示 最後までタップして贈り物を購入し一度だけ保存',async()=>{const s=requestFixture();await fresh(s);await tap('resume');assert.equal(await page.locator('.novel-stage').count(),1);assert.equal(await page.locator('[data-action="novelExit"]').count(),0);await last('requestChoice');await fit();await page.screenshot({path:path.join(root,'previews/v108-affinity-request.png')});const q=s.career.affinity.requests[0];await tap('requestChoice',q.id+'|0');assert.equal(await page.evaluate(()=>KM_APP.getState().career.player.money),150-q.cost);assert.equal(await page.evaluate(()=>KM_APP.getState().career.bonds.heroines.akari.affection),42);await page.reload();await tap('resume');assert.equal(await page.locator('[data-action="requestChoice"]').count(),0);assert.equal(await page.evaluate(()=>KM_APP.getState().career.affinity.requests[0].status),'fulfilled');});
await run('着順の約束を出走前へ表示 即結果の精算でも達成可否と好感度を反映',async()=>{const s=requestFixture('race'),c=s.career,q=c.affinity.requests[0];E.Affinity.reply(c,q.id,0);c.status='preRace';await fresh(s);await tap('resume');assert.match(await page.locator('.relationship-promise').innerText(),/次の公式レースで [23]着以内/);await tap('instantRace');await page.waitForFunction(()=>KM_APP.getState().career.status==='raceResult',{timeout:20000});await page.locator('.affinity-result').waitFor();const z=await page.evaluate(()=>{const c=KM_APP.getState().career;return {request:c.affinity.requests[0],result:c.lastResult};});assert.equal(z.request.status,!z.result.startFault&&!z.result.dnf&&!z.result.capsized&&z.result.place<=q.target?'fulfilled':'missed');assert.match(await page.locator('.affinity-result').innerText(),/汐見 灯/);await fit();await page.screenshot({path:path.join(root,'previews/v108-affinity-result.png'),fullPage:true});});
for(const file of ['index_android_safe.html','index_iphone_safe.html'])await run(file+' 単体の好感度と強制依頼を表示し保存復元',async()=>{const s=requestFixture();await fresh(s,file,360,740);await tap('resume');await last('requestChoice');assert.ok(await page.locator('.novel-cast img').evaluate(n=>n.complete&&n.naturalWidth>0&&n.src.startsWith('data:image/')));await fit();await tap('requestChoice',s.career.affinity.requests[0].id+'|1');await page.reload();assert.equal(await page.evaluate(()=>KM_APP.getState().career.affinity.requests[0].status),'declined');await tap('resume');assert.match(await page.locator('#app').innerText(),/好感度/);});
await run('起動 会話 特訓 スキップ 保存復元で未処理エラーなし',async()=>assert.deepEqual(errors,[]));
await browser.close();const report={build:108,passed:results.filter(x=>x.passed).length,failed:results.filter(x=>!x.passed).length,results,browser:'Chromium mobile touch emulation 390x844 and 360x740',androidDeviceTested:false,iphoneDeviceTested:false,safariTested:false};fs.writeFileSync(path.join(root,'tests/browser-v108-results.json'),JSON.stringify(report,null,2));if(report.failed)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1;});
