'use strict';
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),E=require('../script');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
const root=path.resolve(__dirname,'..'),results=[],errors=[];
function fixture(stage=6){const s=E.newState(49);E.createCareer(s,E.character(s,'水城 遥'));s.career.stage=stage;if(stage){E.startSeries(s);E.prepareRace(s);}s.settings.presentation='off';s.settings.haptics=false;for(const h of Object.values(s.career.bonds.heroines))Object.assign(h,{met:true,metRace:0,metStage:0});return s;}
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.KM_TEST_BROWSER||'/tmp/v105-browser/chrome-headless-shell-linux64/chrome-headless-shell',env:{...process.env,FONTCONFIG_FILE:'/tmp/v105-fonts.conf'},args:['--no-sandbox']});let ctx,page;
async function run(name,fn){if(process.env.KM_TEST_FILTER&&!name.includes(process.env.KM_TEST_FILTER))return;try{await fn();results.push({name,passed:true});console.log('PASS',name);}catch(e){results.push({name,passed:false,error:e.stack});console.error('FAIL',name,e.message);}}
async function fresh(s=fixture(),file='index.html',width=390,height=844){if(ctx)await ctx.close();ctx=await browser.newContext({viewport:{width,height},isMobile:true,hasTouch:true,deviceScaleFactor:1});page=await ctx.newPage();page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(String(e)));await page.addInitScript(s=>{window.__clicks={};document.addEventListener('click',e=>{const a=e.target.closest('[data-action]')?.dataset.action;if(a)window.__clicks[a]=(window.__clicks[a]||0)+1;},true);if(!localStorage.getItem('kyotei_monogatari_v80'))localStorage.setItem('kyotei_monogatari_v80',JSON.stringify(s));},s);await page.goto('file://'+path.join(root,file));await page.waitForFunction(()=>!!window.KM_APP);assert.equal(await page.evaluate(()=>KM_ENGINE.D.build),'112');}
const tap=async(a,v)=>{const n=await page.evaluate(a=>window.__clicks[a]||0,a);await page.locator('[data-action="'+a+'"]'+(v!==undefined?'[data-value="'+v+'"]':'')).first().tap();await page.waitForFunction(([a,n])=>(window.__clicks[a]||0)>n,[a,n]);};
const fit=async()=>assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
const ended=async()=>{await page.waitForFunction(()=>!document.querySelector('.novel-stage'));await fit();};
async function last(action){for(let i=0;i<100;i++){if(await page.locator('[data-action="'+action+'"]').count())return;await tap('novelNext');}throw Error('Missing choice '+action);}
async function choice(action,index=0){await last(action);const value=await page.locator('[data-action="'+action+'"]').nth(index).getAttribute('data-value');await tap(action,value);return value;}
async function shot(name){await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(root,'previews/v112-'+name+'.png'),fullPage:true});}
await run('390px ライバル選択後の閉じると再読込で会話が再出現しない',async()=>{await fresh();await tap('resume');await tap('mainRival');await choice('rivalChoice');await shot('reply');await tap('novelExit');await ended();const persisted=await page.evaluate(()=>{const raw=localStorage.getItem('kyotei_monogatari_v80');try{return {valid:KM_ENGINE.validState(JSON.parse(raw)),decoded:KM_ENGINE.decode(raw).career.development.rival,live:KM_APP.getState().career.development.rival};}catch(e){return {error:e.message,raw:JSON.parse(raw),live:KM_APP.getState().career.development.rival};}});assert.ok(!persisted.error,persisted.error);assert.deepEqual(persisted.decoded,persisted.live);const saved=persisted.live;await page.reload();await tap('resume');await ended();assert.deepEqual(await page.evaluate(()=>KM_APP.getState().career.development.rival),saved);});
await run('本編選択後は章一覧へ戻り本文へループしない',async()=>{const s=fixture(0);await fresh(s);await tap('resume');await tap('campaign',s.career.player.id);await choice('campaignChoice');await tap('novelExit');await ended();assert.match(await page.locator('#modal').innerText(),/物語の章/);});
await run('360px 師匠会話を途中で閉じ 読んだ位置から再開 選択後も閉じられる',async()=>{await fresh(fixture(),'index.html',360,740);await tap('resume');await tap('bonds');await tap('mentor');await tap('mentorMeet');await tap('novelNext');const text=await page.locator('.novel-text').innerText();await tap('novelExit');await ended();await tap('mentorMeet');assert.equal(await page.locator('.novel-text').innerText(),text);await choice('mentorChoice');await tap('novelExit');await ended();await shot('mentor-return');});
await run('320px ヒロイン返答から依頼へ続き 選択後は出走準備へ戻る',async()=>{const s=fixture();s.career.affinity.seed=1;await fresh(s,'index.html',320,700);await tap('resume');await tap('bonds');await tap('meet','akari');await choice('bondChoice');assert.ok(await page.evaluate(()=>KM_ENGINE.Affinity.offer(KM_APP.getState().career)));await tap('novelExit');assert.equal(await page.locator('[data-action="novelExit"]').count(),0);await choice('requestChoice',1);await fit();await tap('novelExit');await ended();assert.equal(await page.evaluate(()=>KM_ENGINE.Affinity.offer(KM_APP.getState().career)),null);});
for(const file of ['index_android_safe.html','index_iphone_safe.html'])await run(file+' 人物画像と選択返答を表示 閉じて保存再開',async()=>{const s=fixture();s.career.affinity.rolled=['akari:1'];await fresh(s,file,360,740);await tap('resume');await tap('bonds');await tap('meet','akari');assert.ok(await page.locator('.novel-cast img').evaluate(n=>n.complete&&n.naturalWidth>0&&n.src.startsWith('data:image/')));await choice('bondChoice');await tap('novelExit');await ended();const before=await page.evaluate(()=>KM_APP.getState().career.bonds.heroines.akari);const stored=await page.evaluate(()=>KM_ENGINE.decode(localStorage.getItem('kyotei_monogatari_v80')).career.bonds.heroines.akari);assert.deepEqual(stored,before);await page.reload();await tap('resume');await ended();const after=await page.evaluate(()=>({state:KM_APP.getState(),raw:localStorage.getItem('kyotei_monogatari_v80'),text:document.getElementById('app').innerText,persistent:KM_APP.safeStorage.persistent}));assert.deepEqual(after.state.career.bonds.heroines.akari,before);});
for(const mode of ['auto','canvas'])await run('390px '+mode+'描画 ボート ブイ 水面を表示し操船を開始',async()=>{const s=fixture();s.career.status='preRace';s.career.story.pending=null;s.settings.renderMode=mode;s.settings.guide=false;await fresh(s);await tap('resume');await page.evaluate(()=>{const create=KM_RACE_RENDERER.create;KM_RACE_RENDERER.create=(...a)=>{const r=create(...a);window.__renderMode=r.mode;const draw=r.draw;r.draw=(...a)=>{draw(...a);window.__frames=(window.__frames||0)+1;};return r;};});await tap('start');await page.waitForFunction(()=>window.__frames>0);assert.equal(await page.evaluate(()=>window.__renderMode),mode==='canvas'?'canvas':'webgl');await page.locator('[data-drive="resume"]').tap();await page.waitForFunction(()=>KM_APP.getState().career.series.race.drive.paused===false);await page.waitForFunction(()=>window.__frames>=4);assert.ok(await page.locator('#water-canvas').evaluate(n=>n.width>0&&n.height>0));await fit();await shot('browser-'+mode);await page.locator('[data-drive="pause"]').tap();await page.waitForFunction(()=>KM_APP.getState().career.series.race.drive.paused===true);});
await run('全画面の未処理JavaScriptエラーなし',async()=>assert.deepEqual(errors,[]));
await browser.close();const report={build:112,passed:results.filter(x=>x.passed).length,failed:results.filter(x=>!x.passed).length,results,browser:'Chromium mobile touch emulation 390x844 360x740 320x700',androidDeviceTested:false,iphoneDeviceTested:false,safariTested:false};fs.writeFileSync(path.join(root,'tests/browser-v112-results.json'),JSON.stringify(report,null,2));if(report.failed)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1;});
