'use strict';
const path=require('path'),fs=require('fs'),assert=require('node:assert/strict'),E=require('../script');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
const results=[],root=path.resolve(__dirname,'..'),errors=[];
const snapshot=()=>{const s=E.newState(31),p=E.character(s,'水瀬 湊');p.scenario='back';E.createCareer(s,p);s.career.campaign.arc=s.career.player.scenario='back';E.startSeries(s);E.prepareRace(s);s.settings.presentation='off';return s;};
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.KM_TEST_BROWSER||'/tmp/v105-browser/chrome-headless-shell-linux64/chrome-headless-shell',env:{...process.env,FONTCONFIG_FILE:'/tmp/v105-fonts.conf'},args:['--no-sandbox']});
async function run(name,fn){try{await fn();results.push({name,passed:true});}catch(e){results.push({name,passed:false,error:e.stack});console.error(name,e.message);}}
let ctx,page;
async function fresh(file='index.html',state=snapshot(),width=390,height=844){if(ctx)await ctx.close();ctx=await browser.newContext({viewport:{width,height},deviceScaleFactor:1,isMobile:true,hasTouch:true});page=await ctx.newPage();page.setDefaultTimeout(8000);page.on('pageerror',e=>errors.push(String(e)));await page.addInitScript(s=>{localStorage.setItem('kyotei_monogatari_v80',JSON.stringify(s));},state);await page.goto('file://'+path.join(root,file));await page.waitForFunction(()=>!!window.KM_APP);return page;}
const tap=async(a,v)=>{const q='[data-action="'+a+'"]'+(v!==undefined?'[data-value="'+v+'"]':'');await page.locator(q).first().tap();};
async function nextToChoice(action){for(let i=0;i<60;i++){if(await page.locator('[data-action="'+action+'"]').count())return;await tap('novelNext');}throw Error('Choice not reached');}
await run('分割版をAndroid相当幅で起動し練習と整備を1回ずつ実行',async()=>{await fresh();await tap('resume');assert.equal(await page.locator('#toast').evaluate(n=>n.classList.contains('visible')),false);assert.equal(await page.locator('.adjust-directions button').first().evaluate(n=>getComputedStyle(n).display),'block');await tap('train','speed');assert.equal(await page.evaluate(()=>KM_APP.getState().career.series.action.training),0);await tap('tune','motor:balanced');assert.equal(await page.evaluate(()=>KM_APP.getState().career.series.action.tune),0);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);});
await run('会話は1頁ずつ進み最後まで選択肢が出ず二重報酬もない',async()=>{await fresh();await tap('resume');await tap('planOpen');assert.equal(await page.locator('[data-action="planChoice"]').count(),0);await page.locator('.novel-cast img').evaluateAll(ns=>Promise.all(ns.map(n=>n.decode().catch(()=>{}))));await page.screenshot({path:path.join(root,'previews/v106-story.png'),fullPage:true});await nextToChoice('planChoice');await tap('planChoice','0');assert.equal(await page.evaluate(()=>KM_APP.getState().career.development.plans.length),1);await tap('novelExit');await tap('development');await page.locator('.novel-cast img').evaluateAll(ns=>Promise.all(ns.map(n=>n.decode().catch(()=>{}))));await page.screenshot({path:path.join(root,'previews/v106-development.png'),fullPage:true});});
await run('実ブラウザ再起動で本編の読書位置が維持される',async()=>{await fresh();const id=await page.evaluate(()=>KM_APP.getState().career.player.id);await tap('resume');await tap('stories');await tap('campaign',id);await tap('novelNext');const text=await page.locator('.novel-text').textContent(),raw=await page.evaluate(()=>KM_APP.export());await fresh('index.html',JSON.parse(raw));await tap('resume');await tap('stories');await tap('campaign',id);assert.equal(await page.locator('.novel-text').textContent(),text);await tap('novelPrev');assert.notEqual(await page.locator('.novel-text').textContent(),text);});
await run('恋愛会話・人物画像・返答後の会話を同じリーダーで表示',async()=>{const s=snapshot(),q=s.career.bonds.heroines.akari;q.met=true;q.metRace=0;q.metStage=0;await fresh('index.html',s);await tap('resume');await tap('bonds');await tap('meet','akari');assert.equal(await page.locator('.novel-cast img').getAttribute('data-portrait'),'akari');assert.equal(await page.locator('[data-action="bondChoice"]').count(),0);await nextToChoice('bondChoice');await page.locator('.novel-cast img').evaluateAll(ns=>Promise.all(ns.map(n=>n.decode().catch(()=>{}))));assert.equal(await page.locator('.sound-controls').evaluate(n=>getComputedStyle(n).position),'absolute');assert.ok(await page.evaluate(()=>document.querySelector('.sound-controls').getBoundingClientRect().bottom<document.querySelector('.novel-top h2').getBoundingClientRect().top));await page.screenshot({path:path.join(root,'previews/v106-heroine.png'),fullPage:true});await page.locator('[data-action="bondChoice"]').first().tap();assert.ok(await page.locator('.novel-stage').count());assert.equal(await page.evaluate(()=>KM_APP.getState().career.bonds.log.filter(x=>x.kind==='romance').length),1);});
await run('師匠会話から閉じて再開しても同じ頁に戻る',async()=>{const s=snapshot(),c=s.career;c.stage=2;c.status='home';E.startSeries(s);await fresh('index.html',s);await tap('resume');await tap('mentor');await tap('mentorMeet');await tap('novelNext');const text=await page.locator('.novel-text').textContent();await tap('novelExit');await tap('mentorMeet');assert.equal(await page.locator('.novel-text').textContent(),text);});
await run('360px・短い画面・大きな文字でも本文が横にはみ出さない',async()=>{const s=snapshot();s.settings.textSize='large';await fresh('index.html',s,360,640);await tap('resume');await tap('planOpen');await nextToChoice('planChoice');assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);const box=await page.locator('.novel-box').boundingBox();assert.ok(box.width<=360);await page.locator('.novel-cast img').evaluateAll(ns=>Promise.all(ns.map(n=>n.decode().catch(()=>{}))));await page.screenshot({path:path.join(root,'previews/v106-small.png'),fullPage:true});});
await run('Android Safe単体で会話 背景 人物を外部通信なしで表示',async()=>{await fresh('index_android_safe.html');await tap('resume');await tap('planOpen');const src=await page.locator('.novel-cast img').getAttribute('src');assert.ok(src.startsWith('data:image/'));assert.ok(await page.locator('.novel-backdrop').evaluate(n=>getComputedStyle(n).backgroundImage.includes('data:image/')));assert.ok(await page.locator('.novel-cast img').evaluate(n=>n.complete&&n.naturalWidth>0));});
await run('iPhone Safe単体を390px幅で起動し本文送りを実行',async()=>{await fresh('index_iphone_safe.html');await tap('resume');await tap('planOpen');const before=await page.locator('.novel-text').textContent();await tap('novelNext');assert.notEqual(await page.locator('.novel-text').textContent(),before);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);});
await run('本編の成長機会から本文とテーマ選択へ進み選択後に通知から消える',async()=>{await fresh();await tap('resume');assert.ok(await page.locator('.opportunity-tray').count());await tap('opportunities');await tap('opportunityGo','main');assert.equal(await page.locator('[data-action="campaignChoice"]').count(),0);await page.locator('.novel-cast img').evaluateAll(ns=>Promise.all(ns.map(n=>n.decode().catch(()=>{}))));await page.screenshot({path:path.join(root,'previews/v106-main.png'),fullPage:true});await nextToChoice('campaignChoice');await page.screenshot({path:path.join(root,'previews/v106-choice.png'),fullPage:true});await tap('campaignChoice','opening|0');assert.ok(await page.evaluate(()=>KM_APP.getState().career.campaign.entries[0].decision));await tap('novelExit');await tap('novelExit');await page.locator('button[data-action="closeModal"]').tap();await tap('resume');await tap('opportunities');assert.equal(await page.locator('[data-action="opportunityGo"][data-value="main"]').count(),0);});
await run('師匠の最終選択を誤ると会話を完走してもLRを渡さず結果を明記',async()=>{const s=snapshot(),c=s.career;c.stage=2;c.status='home';E.startSeries(s);E.Cast.select(c,'hayase');for(let i=0;i<4;i++){c.stage=E.Cast.routes.hayase.chapters[i].stage;c.series.stage=c.stage;c.stats.races=Math.max(c.stats.races,E.Cast.routeState(c).nextAt);const sc=E.Cast.routeOpen(c);E.chooseMentor(c,sc.key,E.Drama.B.mentor.hayase[i].correct);}c.stage=8;c.series.stage=8;c.stats.races=c.cast.route.nextAt;await fresh('index.html',s);await tap('resume');await tap('mentor');await tap('mentorMeet');await nextToChoice('mentorChoice');const q=await page.evaluate(()=>KM_APP.getState().career.cast.route.pending.key);await tap('mentorChoice',q+'|1');assert.equal(await page.evaluate(()=>KM_APP.getState().career.cast.route.reward),null);for(let i=0;i<20;i++){const t=await page.locator('.novel-text').textContent();if(t.includes('今回は伝授なし'))break;await tap('novelNext');}assert.match(await page.locator('.novel-text').textContent(),/今回は伝授なし/);await page.screenshot({path:path.join(root,'previews/v106-mentor-outcome.png'),fullPage:true});});
await run('未回収一覧は期限を示し長い日本語でも360px幅を越えない',async()=>{const s=snapshot(),c=s.career,e=E.Drama.B.daily[0],r=c.series.race;c.story.pending={kind:'event',id:e.id,key:r.id+':'+e.id,raceId:r.id,variant:0};await fresh('index.html',s,360,640);await tap('resume');await tap('opportunities');assert.match(await page.locator('#modal').textContent(),/出走まで/);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:path.join(root,'previews/v106-opportunities.png'),fullPage:true});await tap('opportunityGo','event');assert.ok(await page.locator('.novel-stage').count());});
await run('各画面でJavaScript例外が発生しない',()=>assert.deepEqual(errors,[]));
await browser.close();const report={build:106,passed:results.filter(x=>x.passed).length,failed:results.filter(x=>!x.passed).length,browser:'Chromium headless stable',realBrowser:true,realAndroidDevice:false,realIPhoneDevice:false,results};fs.writeFileSync(path.join(__dirname,'browser-v106-results.json'),JSON.stringify(report,null,2));console.log({passed:report.passed,failed:report.failed});process.exitCode=report.failed?1:0;
})().catch(e=>{console.error(e);process.exitCode=1});
