const{chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict');
const E=require('../src/script');const output=path.resolve(__dirname,'../work120/screens');fs.mkdirSync(output,{recursive:true});
const modes=process.argv.includes('--release')?[['release-v120/index_android_safe.html',360,800],['release-v120/index_iphone_safe.html',393,852],['release-v120/web/index.html',1280,900]]:[['index.html',390,844]];
(async()=>{const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE||'/workspace/scratch/7e276fc3919e/pw-browsers/chromium_headless_shell-1161/chrome-linux/headless_shell',headless:true,args:['--no-sandbox']});const results=[];
for(const[file,width,height]of modes){const context=await browser.newContext({viewport:{width,height},deviceScaleFactor:1,isMobile:width<700,hasTouch:width<700});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const base='http://127.0.0.1:8765/'+file;async function font(){await page.addStyleTag({content:"@font-face{font-family:QAJP;src:url('/tests/qa-japanese.otf')}body,button,input,select{font-family:QAJP,sans-serif!important}"});await page.evaluate(()=>document.fonts.ready)}async function load(s){await page.evaluate(raw=>localStorage.setItem('kyotei_monogatari_v80',raw),JSON.stringify(s));await page.reload();await page.waitForFunction(()=>!!window.KM_APP);await font();await page.locator('[data-action=resume]').first().click();}
await page.goto(base);await page.waitForFunction(()=>!!window.KM_APP);await font();assert.equal(await page.evaluate(()=>KM_APP.getState().build),'120');await page.screenshot({path:path.join(output,'title-'+width+'.png'),fullPage:true});
await page.locator('[data-action=new]').click();await page.locator('#scenario-select').selectOption('recovery');await page.locator('#recovery-origin').selectOption('start');await page.locator('[data-action=create]').click();assert.equal(await page.evaluate(()=>KM_APP.getState().career.refinement.recovery.origin),'start');
await page.locator('[data-action=campaign]').click();const face=page.locator('.novel-cast .portrait-face');await face.waitFor();assert.equal(await face.getAttribute('data-portrait'),'rival_03');assert.ok(await face.getAttribute('data-emotion'));await page.screenshot({path:path.join(output,'story-'+width+'.png')});const bounds=await page.locator('.novel-close').boundingBox();assert.ok(bounds.x>=0&&bounds.x+bounds.width<=width&&bounds.y>=0);
for(let i=0;i<80&&!await page.locator('[data-action=campaignChoice]').count();i++)await page.locator('[data-action=novelNext]').click();assert.equal(await page.locator('[data-action=campaignChoice]').count(),2);await page.locator('[data-action=campaignChoice]').nth(1).click();await page.locator('[data-action=novelExit]').click();await page.locator('[data-action=resume]').click();
// Practice must never mutate the career, even after changing local control options and finishing.
const before=await page.evaluate(()=>KM_APP.export());await page.locator('[data-action=practice]').first().click();await page.screenshot({path:path.join(output,'practice-'+width+'.png'),fullPage:true});await page.locator('[data-action=practiceStart][data-value=start]').click();assert.match(await page.locator('.drive-dialog').innerText(),/練習区間で終了/);await page.locator('[data-drive=resume]').click();await page.keyboard.down('w');await page.waitForSelector('[data-action=practiceRetry]',{timeout:30000});await page.keyboard.up('w');assert.equal(await page.evaluate(()=>KM_APP.export()),before);await page.screenshot({path:path.join(output,'practice-result-'+width+'.png'),fullPage:true});await page.locator('[data-action=practiceRetry]').click();await page.locator('[data-drive=exit]').click();assert.equal(await page.evaluate(()=>KM_APP.export()),before);await page.locator('[data-action=practiceBack]').click();
// Sound controls are independent and persisted.
await page.locator('.sound-controls summary').click();for(const[k,v]of [['bgmVolume',.25],['sfxVolume',.55],['engineVolume',.15]])await page.locator('#sound-'+k).evaluate((el,v)=>{el.value=v;el.dispatchEvent(new Event('change',{bubbles:true}))},v);assert.deepEqual(await page.evaluate(()=>{const p=KM_AUDIO.diagnostics();return[p.bgmVolume,p.sfxVolume,p.engineVolume]}),[.25,.55,.15]);await page.locator('.sound-controls summary').click();
await page.locator('[data-action=series]').click();await page.locator('[data-action=prepare]').click();await page.locator('[data-action=pre]').click();await page.locator('[data-action=startPolicy][data-value=attack]').click();assert.equal(await page.evaluate(()=>KM_APP.getState().career.series.race.startPolicy),'attack');await page.screenshot({path:path.join(output,'pre-race-'+width+'.png'),fullPage:true});await page.locator('[data-action=start]').click();await page.locator('[data-drive=resume]').click();await page.keyboard.down('ArrowLeft');await page.waitForFunction(()=>KM_APP.getState().career.series.race.drive.elapsed>.3);await page.keyboard.up('ArrowLeft');const lock=await page.evaluate(()=>{const d=KM_APP.getState().career.series.race.drive,b=d.boats.find(x=>x.isPlayer);return[b.heading,b.steer,b.startTime]});assert.deepEqual(lock,[0,0,null]);await page.screenshot({path:path.join(output,'race-'+width+'.png')});await page.keyboard.press('Escape');await page.reload();await page.waitForFunction(()=>!!window.KM_APP);assert.equal(await page.evaluate(()=>KM_AUDIO.diagnostics().engineVolume),.15);
// Use an actual finished race fixture for review and replay navigation.
const s=E.newState(2118),p=E.character(s,'振り返り選手');p.scenario='recovery';const c=E.createCareer(s,p);E.startSeries(s);E.prepareRace(s);c.status='preRace';E.autoResolve(s);assert.ok(E.validState(s));await load(s);assert.equal(await page.locator('.craft-review').count(),1);await page.screenshot({path:path.join(output,'review-'+width+'.png'),fullPage:true});const jump=page.locator('[data-action=replayMark]');if(await jump.count()){await jump.click();assert.ok(Number(await page.locator('#replay-seek').inputValue())>0);await page.locator('button[data-action=closeModal]').click();}
assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.equal(errors.length,0,errors.join('\n'));results.push({file,width,height,errors,checked:['起動','再起設定','表情と長い題名','両方の本編選択','練習の終了・再挑戦・データ不変','音量の独立保存','スタート方針','直進制限','中断再読込','実測振り返り','該当場面リプレイ','横にはみ出さない']});await context.close();}
fs.writeFileSync(path.resolve(__dirname,'browser-verification-v120'+(process.argv.includes('--release')?'-release':'')+'.json'),JSON.stringify(results,null,2));console.log(JSON.stringify(results));await browser.close()})().catch(e=>{console.error(e);process.exit(1)});
