'use strict';
const path=require('path'),fs=require('fs'),assert=require('node:assert/strict'),E=require('../script'),{fixture}=require('./finale-v107-benchmark.cjs');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');const results=[],root=path.resolve(__dirname,'..'),errors=[];
function snapshot(){const {s}=fixture(41,'normal','kagura','ally');s.settings.presentation='off';s.settings.haptics=false;return s;}
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.KM_TEST_BROWSER||'/tmp/v105-browser/chrome-headless-shell-linux64/chrome-headless-shell',env:{...process.env,FONTCONFIG_FILE:'/tmp/v105-fonts.conf'},args:['--no-sandbox']});let ctx,page;
async function run(name,fn){try{await fn();results.push({name,passed:true});console.log('PASS',name);}catch(e){results.push({name,passed:false,error:e.stack});console.error('FAIL',name,e.message);}}
async function fresh(file='index.html',s=snapshot(),width=390,height=844){if(ctx)await ctx.close();ctx=await browser.newContext({viewport:{width,height},deviceScaleFactor:1,isMobile:true,hasTouch:true});page=await ctx.newPage();page.setDefaultTimeout(8000);page.on('pageerror',e=>errors.push(String(e)));await page.addInitScript(s=>{if(!localStorage.getItem('kyotei_monogatari_v80'))localStorage.setItem('kyotei_monogatari_v80',JSON.stringify(s));},s);await page.goto('file://'+path.join(root,file));await page.waitForFunction(()=>!!window.KM_APP);return page;}
const tap=async(a,v)=>page.locator('[data-action="'+a+'"]'+(v!==undefined?'[data-value="'+v+'"]':'')).first().tap();
const fit=async()=>assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
await run('390px 決戦の6艇とSS120を表示 新しい顔画像を読み込み',async()=>{await fresh();await tap('resume');await page.locator('.finale-grid img').first().waitFor();assert.equal(await page.locator('.finale-grid img').count(),5);assert.ok(await page.locator('.finale-grid').innerText().then(t=>t.includes('挺王')&&t.includes('朝凪 瑞希')));await fit();assert.ok(await page.locator('.finale-grid img').evaluateAll(a=>a.every(x=>x.complete&&x.naturalWidth>0)));await page.screenshot({path:path.join(root,'previews/v107-final-grid.png'),fullPage:true});await tap('pre');assert.ok((await page.locator('#app').innerText()).includes('120 SS'));await fit();});
await run('実描画上で2人のセリフを表示 操作エリアと重ならず入力を遮らない',async()=>{await tap('start');await page.evaluate(()=>{const tick=KM_RACING.tick;let once=false;KM_RACING.tick=(d,r,input,dt,ai)=>{const z=tick(d,r,input,dt,ai);if(!once){once=true;d.elapsed=30;d.started=true;d.countdown=0;for(const b of d.boats){b.startTime=.15;const progress=680+b.frame*3,pos=KM_RACING.pointAt(KM_RACING.C.start+progress,42+b.frame*2);Object.assign(b,pos,{progress,lastS:KM_RACING.project(pos.x,pos.z).s,vx:Math.cos(pos.heading)*18,vz:Math.sin(pos.heading)*18,speed:18,checkpoints:8});}d.events=[];for(const id of ['cast_teiou','mizuki']){const b=d.boats.find(b=>b.id===id),a=KM_DATA.abilityMap[b.skills[0]];d.events.push({index:d.eventSequence++,t:d.elapsed,kind:'ability',phase:2,athleteId:b.id,name:b.name,frame:b.frame,abilityId:a.id,rarity:a.rarity,category:a.category});}}return z;};});await page.locator('[data-drive="resume"]').tap();await page.waitForFunction(()=>document.querySelectorAll('.race-voice').length===2);assert.ok(await page.locator('.race-voices').evaluate(el=>getComputedStyle(el).pointerEvents==='none'&&el.getBoundingClientRect().bottom<innerHeight*.5));await page.screenshot({path:path.join(root,'previews/v107-race-dialogue.png')});assert.ok(await page.locator('#water-canvas').evaluate(c=>c.width>0&&c.height>0));await page.locator('[data-drive="pause"]').tap();assert.equal(await page.locator('.race-voice').count(),0);});
await run('ゴール線通過で即FINISHと固定タイム その後も船体が進む',async()=>{await fresh();await tap('resume');await tap('pre');await tap('start');await page.evaluate(()=>{const tick=KM_RACING.tick;let once=false;KM_RACING.tick=(d,r,input,dt,ai)=>{const z=tick(d,r,input,dt,ai);if(!once){once=true;const b=KM_RACING.own(d),gx=KM_RACING.pointAt(KM_RACING.C.start).x;d.elapsed=100;d.started=true;d.countdown=0;Object.assign(b,{startTime:.15,startFault:null,dnf:false,capsized:false,stress:0,stamina:100,checkpoints:23,progress:1799,x:gx-3.4,z:45,heading:0,vx:20,vz:0,speed:20});const crossed=KM_RACING.finishCrossing(d,b,gx-.1);window.__finishBefore={x:b.x,time:b.finishTime,crossed};}return z;};});await page.locator('[data-drive="resume"]').tap();await page.waitForFunction(()=>!!window.__finishBefore);const before=await page.evaluate(()=>window.__finishBefore);assert.equal(before.crossed,true);await page.waitForFunction(()=>document.getElementById('drive-warning')?.textContent.includes('FINISH'));const after=await page.evaluate(()=>{const b=KM_RACING.own(KM_APP.getState().career.series.race.drive);return {x:b.x,time:b.finishTime,speed:b.speed};});assert.ok(after.x>before.x);assert.equal(after.time,before.time);assert.ok(after.speed>0);await page.screenshot({path:path.join(root,'previews/v107-finish-runout.png')});});
await run('3秒ずつ進む観戦でも対戦セリフと先駆スタートを確認',async()=>{const s=E.newState(5),p=E.character(s,'観戦確認');E.createCareer(s,p);const c=s.career;c.stage=8;c.player.totalEarnings=1800;E.startSeries(s);c.cast.boss.id='kagura';c.series.round=c.cast.schedule.round;E.prepareRace(s);c.status='preRace';await fresh('index.html',s);await tap('resume');await tap('skipRace');if(await page.locator('[data-action="auto"]').innerText().then(t=>t.includes('止める')))await tap('auto');let seen=false;for(let i=0;i<5;i++){await tap('advance');if(await page.locator('.race-voice').count())seen=true;}assert.ok(seen);assert.equal(await page.evaluate(()=>KM_APP.getState().career.series.race.drive.boats.find(b=>b.castId==='kagura').startFault),null);await fit();await page.screenshot({path:path.join(root,'previews/v107-spectator.png'),fullPage:true});});
await run('新ヒロインも背景と顔を伴うタップ式会話で表示',async()=>{const s=snapshot(),c=s.career;Object.assign(c.bonds.heroines.mizuki,{met:true,metStage:0,metRace:1,step:0,trust:0,affection:0,choices:[]});await fresh('index.html',s);await tap('resume');await tap('bonds');await tap('meet','mizuki');await page.locator('img[data-portrait="mizuki"]').first().waitFor();await fit();assert.ok((await page.locator('#app').innerText()).includes('負けた側のリプレイ'));await page.screenshot({path:path.join(root,'previews/v107-mizuki-story.png')});});
await run('主ライバルの分岐は最後まで読んで選択し保存される',async()=>{const s=E.newState(9),p=E.character(s,'主ライバル検証');E.createCareer(s,p);const c=s.career;c.stage=4;E.startSeries(s);c.development.rival.history=[{raceId:'a',stage:0,type:'qualifier',won:true,place:1,other:2},{raceId:'b',stage:2,type:'qualifier',won:false,place:3,other:1}];await fresh('index.html',s);await tap('resume');await tap('opportunities');await tap('opportunityGo','rival-path');assert.equal(await page.locator('[data-action="rivalPathChoice"]').count(),0);for(let i=0;i<60;i++){if(await page.locator('[data-action="rivalPathChoice"]').count())break;await tap('novelNext');}await tap('rivalPathChoice','1');assert.equal(await page.evaluate(()=>KM_APP.getState().career.finale.rival.route),'ally');await page.reload();assert.equal(await page.evaluate(()=>KM_APP.getState().career.finale.rival.route),'ally');});
for(const file of ['index_android_safe.html','index_iphone_safe.html'])await run(file+' を360pxで起動し 新ポートレートと決戦を表示',async()=>{await fresh(file,snapshot(),360,740);await tap('resume');await fit();assert.equal(await page.locator('.finale-grid img').count(),5);assert.ok(await page.locator('.finale-grid img').evaluateAll(a=>a.every(x=>x.src.startsWith('data:image/')&&x.complete&&x.naturalWidth>0)));await tap('pre');await tap('start');assert.equal(await page.locator('#race-voices').count(),1);await page.screenshot({path:path.join(root,'previews/v107-'+(file.includes('iphone')?'iphone':'android')+'.png')});});
await run('起動・会話・操船で未処理JavaScriptエラーなし',async()=>assert.deepEqual(errors,[]));
await browser.close();const report={build:107,passed:results.filter(x=>x.passed).length,failed:results.filter(x=>!x.passed).length,results,browser:'Chromium headless mobile emulation',androidDeviceTested:false,iphoneDeviceTested:false,safariTested:false};fs.writeFileSync(path.join(root,'tests/browser-v107-results.json'),JSON.stringify(report,null,2));if(report.failed)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1;});
