const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const E=require('../src/script'),C=E.Coaching;
const report={build:E.D.build,checks:[]};
function test(name,fn){fn();report.checks.push(name)}
function disk(initial={}){let failure=null;const values=new Map(Object.entries(initial));return {values,fail(value){failure=value},getItem(k){if(failure==='read')throw Error('unavailable');return values.get(k)??null},setItem(k,v){if(failure)throw Object.assign(Error(failure),{name:failure==='quota'?'QuotaExceededError':'SecurityError'});values.set(k,String(v))},removeItem(k){if(failure)throw Error('unavailable');values.delete(k)}}}
test('容量不足でも既存セーブを読み出す',()=>{const d=disk({save:'existing'});d.fail('quota');const s=C.createStorage(()=>d,'save');assert.equal(s.persistent,false);assert.equal(s.failure.kind,'capacity');assert.equal(s.get('save'),'existing');assert.equal(s.set('save','new'),false);assert.equal(s.get('save'),'new');assert.equal(d.values.get('save'),'existing');d.fail(null);assert.equal(s.retry(),true);assert.equal(s.persistent,true);assert.equal(s.get('save'),'new')});
test('途中の書込失敗から最新値と削除をまとめて復旧',()=>{const d=disk({obsolete:'old'}),s=C.createStorage(()=>d,'save');let notifications=0;s.subscribe(()=>notifications++);assert.equal(s.set('save','first'),true);d.fail('quota');assert.equal(s.set('save','second'),false);assert.equal(s.set('save','latest'),false);assert.equal(s.set('backup','second'),false);assert.equal(s.remove('obsolete'),false);assert.equal(s.get('obsolete'),null);assert.equal(s.retry(),false);d.fail(null);assert.equal(s.retry(),true);assert.equal(s.get('save'),'latest');assert.equal(s.get('backup'),'second');assert.equal(d.values.has('obsolete'),false);assert.ok(notifications>=3)});
test('保存領域へのアクセス拒否でもメモリー内で続行・再試行',()=>{let denied=true;const d=disk(),s=C.createStorage(()=>{if(denied)throw Error('denied');return d},'save');s.set('save','data');assert.equal(s.get('save'),'data');assert.equal(s.retry(),false);denied=false;assert.equal(s.retry(),true);assert.equal(d.values.get('save'),'data')});
test('読出失敗時は既読値を維持し、新しい値を保留',()=>{const d=disk({save:'first'}),s=C.createStorage(()=>d,'save');assert.equal(s.get('save'),'first');d.fail('read');assert.equal(s.get('save'),'first');s.set('save','new');d.fail(null);assert.equal(s.retry(),true);assert.equal(s.get('save'),'new')});
const s=E.newState(121),p=E.character(s,'検証選手');p.scenario='light';const c=E.createCareer(s,p);E.startSeries(s);E.prepareRace(s);
test('診断は表示だけで状態と乱数を変えない',()=>{const before=JSON.stringify(s);for(let i=0;i<100;i++){C.support(c.player);C.advice(c)}assert.equal(JSON.stringify(s),before)});
test('基礎直線換算は実際のエンジンの式と一致',()=>{for(const speed of [35,65,100])for(const accel of [20,60,100])for(const power of [35,75,100]){const p={stats:{speed,accel,power}},v=C.support(p);assert.equal(v.effective,E.R.straightSupport(p.stats).effective);for(const a of v.alternatives)assert.equal(a.effective,E.R.straightSupport({...p.stats,[a.key]:p.stats[a.key]+a.amount}).effective)}});
test('前走の観測に応じて操作練習を選ぶ',()=>{for(const [z,drill] of [[{startFault:'F'},'start'],[{capsized:true},'turn'],[{driving:{metrics:{slideSeconds:4}}},'turn'],[{driving:{metrics:{wakeSeconds:5}}},'wake'],[{driving:{metrics:{contacts:1}}},'wake']]){const trial=structuredClone(c);trial.lastResult=z;assert.equal(C.advice(trial).short.drill,drill);assert.equal(C.advice(trial).short.observed,true)}});
test('2つ開花済みなら3つ目の開花を勧めない',()=>{const trial=structuredClone(c);trial.development.paths.speed.branch=0;trial.development.paths.turn.branch=1;const a=C.advice(trial);assert.ok(['speed','turn'].includes(a.long.key));assert.match(a.long.evidence,/開花した技/)});
test('保存最適化は全データとリプレイを保持',()=>{const serialize=C.createSerializer();E.startDrive(c,c.series.race);for(let i=0;i<200;i++)E.R.tick(c.series.race.drive,c.series.race,{},E.R.DT,true);s.registry=[{...structuredClone(c.player),id:'registered',name:'選手',journal:Array.from({length:500},(_,i)=>({id:i,text:'記録'}))}];for(const periodic of [false,true,true]){assert.equal(serialize(s,periodic),JSON.stringify(s));c.player.money+=1}E.syncPlayerSnapshot(c);const raw=serialize(s,true),decoded=E.decode(raw);assert.ok(E.validState(decoded));assert.deepEqual(decoded.career.series.race.drive,c.series.race.drive);s.registry[0].name='編集後';assert.equal(serialize(s,false),JSON.stringify(s));s.registry=[...s.registry,{...structuredClone(c.player),id:'new'}];assert.equal(serialize(s,true),JSON.stringify(s));s.registry.push({...structuredClone(c.player),id:'added'});assert.equal(serialize(s,true),JSON.stringify(s))});
test('V120の中断データと行動残数を引き継ぐ',()=>{const before=structuredClone(s);before.build='120';const after=E.decode(JSON.stringify(before));assert.deepEqual(after.career,before.career);assert.deepEqual(after.registry,before.registry);assert.deepEqual(after.rivals,before.rivals);assert.equal(after.seed,before.seed);assert.equal(after.build,'121')});
fs.writeFileSync(path.join(__dirname,'coaching-v121.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
