const{chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),E=require('../src/script');
const output=path.join(__dirname,'../work120/screens');fs.mkdirSync(output,{recursive:true});
const modes=process.argv.includes('--release')?[['release-v120/index_android_safe.html',360,800],['release-v120/index_iphone_safe.html',393,852],['release-v120/web/index.html',1280,900]]:[['index.html',390,844]];
(async()=>{const browser=await chromium.launch({executablePath:process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE||'/workspace/scratch/7e276fc3919e/pw-browsers/chromium_headless_shell-1161/chrome-linux/headless_shell',headless:true,args:['--no-sandbox']});const report=[];
for(const[file,width,height]of modes){const ctx=await browser.newContext({viewport:{width,height},deviceScaleFactor:1,isMobile:width<700,hasTouch:width<700}),page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));const url='http://127.0.0.1:8765/'+file;
async function boot(){await page.goto(url);await page.waitForFunction(()=>!!window.KM_APP);await page.addStyleTag({content:"@font-face{font-family:QAJP;src:url('/tests/qa-japanese.otf')}body,button,input,select{font-family:QAJP,sans-serif!important}"});await page.evaluate(()=>document.fonts.ready);}
await boot();await page.locator('[data-action=new]').click();assert.equal(await page.locator('#scenario-select').inputValue(),'random');assert.equal(await page.locator('.scenario-card').count(),4);assert.match(await page.locator('.scenario-selection').innerText(),/育成開始時/);
await page.locator('#racer-name').fill('物語を選ぶ選手');await page.locator('input[name=career-difficulty][value=easy]').check();await page.locator('#recovery-origin').selectOption('speed');const seed=await page.evaluate(()=>KM_APP.getState().seed);
for(const id of ['light','back','shore','recovery']){await page.locator('[data-action=scenario][data-value='+id+']').click();assert.equal(await page.locator('#scenario-select').inputValue(),id);assert.equal(await page.locator('#racer-name').inputValue(),'物語を選ぶ選手');assert.equal(await page.locator('#recovery-origin').inputValue(),'speed');assert.ok(await page.locator('input[name=career-difficulty][value=easy]').isChecked());assert.equal(await page.locator('.scenario-card.selected').count(),1);assert.equal(await page.evaluate(()=>KM_APP.getState().seed),seed);}
await page.screenshot({path:path.join(output,'creation-full-'+width+'.png'),fullPage:true});await page.locator('#scenario-select').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(output,'creation-summary-'+width+'.png')});
await page.locator('[data-action=reroll]').click();assert.equal(await page.locator('#scenario-select').inputValue(),'recovery');assert.equal(await page.locator('#recovery-origin').inputValue(),'speed');assert.equal(await page.locator('#racer-name').inputValue(),'物語を選ぶ選手');await page.locator('[data-action=scenario][data-value=random]').click();await page.locator('[data-action=reroll]').click();assert.equal(await page.locator('#scenario-select').inputValue(),'random');await page.locator('#scenario-select').selectOption('recovery');await page.locator('[data-action=create]').click();assert.equal(await page.evaluate(()=>KM_APP.getState().career.campaign.arc),'recovery');assert.equal(await page.evaluate(()=>KM_APP.getState().career.refinement.recovery.origin),'speed');
await page.locator('[data-action=campaign]').click();const before=await page.evaluate(()=>JSON.stringify({p:KM_APP.getState().career.player,b:KM_APP.getState().career.bonds}));for(let n=0;n<7;n++)await page.locator('[data-action=novelNext]').click();const text=await page.locator('.novel-text').innerText();await page.locator('[data-action=novelExit]').click();await page.locator('[data-action=campaign]').click();assert.equal(await page.locator('.novel-text').innerText(),text);assert.equal(await page.evaluate(()=>JSON.stringify({p:KM_APP.getState().career.player,b:KM_APP.getState().career.bonds})),before);for(let n=0;n<90&&!await page.locator('[data-action=campaignChoice]').count();n++)await page.locator('[data-action=novelNext]').click();assert.equal(await page.locator('[data-action=campaignChoice]').count(),2);await page.screenshot({path:path.join(output,'main-choice-'+width+'.png')});
// A met heroine at the first episode: lengthy encounter, close/reopen and save/reload must not advance the relationship.
const s=E.newState(120),p=E.character(s,'出会いの選手');p.scenario='recovery';const c=E.createCareer(s,p);Object.assign(c.bonds.heroines.nagi,{met:true,metStage:0,metRace:0});E.Bonds.open(c,'nagi');assert.ok(E.validState(s));await page.evaluate(raw=>localStorage.setItem('kyotei_monogatari_v80',raw),JSON.stringify(s));await boot();await page.locator('[data-action=resume]').click();await page.locator('[data-action=bonds]').first().click();assert.match(await page.locator('.novel-text').innerText(),/果物/);for(let n=0;n<8;n++)await page.locator('[data-action=novelNext]').click();const body=await page.locator('.novel-text').innerText();await page.locator('[data-action=novelExit]').click();await page.locator('[data-action=meet][data-value=nagi]').click();assert.equal(await page.locator('.novel-text').innerText(),body);await page.reload();await page.waitForFunction(()=>!!window.KM_APP);await page.addStyleTag({content:"@font-face{font-family:QAJP;src:url('/tests/qa-japanese.otf')}body,button,input,select{font-family:QAJP,sans-serif!important}"});await page.evaluate(()=>document.fonts.ready);await page.locator('[data-action=resume]').click();if(!await page.locator('.novel-text').count())await page.locator('[data-action=bonds]').first().click();assert.equal(await page.locator('.novel-text').innerText(),body);assert.equal(await page.evaluate(()=>KM_APP.getState().career.bonds.heroines.nagi.step),0);
for(let n=0;n<90&&!await page.locator('[data-action=bondChoice]').count();n++)await page.locator('[data-action=novelNext]').click();assert.equal(await page.locator('[data-action=bondChoice]').count(),3);await page.screenshot({path:path.join(output,'heroine-choice-'+width+'.png')});for(const selector of ['.novel-close','.novel-choices']){const b=await page.locator(selector).boundingBox();assert.ok(b.x>=0&&b.x+b.width<=width+1&&b.y>=0&&b.y+b.height<=height+1,selector+JSON.stringify(b));}assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.locator('[data-action=bondChoice]').nth(1).click();assert.equal(await page.evaluate(()=>KM_APP.getState().career.bonds.heroines.nagi.step),1);assert.equal(errors.length,0,errors.join('\n'));report.push({file,width,height,errors,passed:['初期ランダム','4概要','任意選択','入力保持','再抽選','閲覧で抽選なし','再起開始','本編中断再開','ヒロイン初対面','保存再読込','読書で好感度加算なし','選択を一度適用','選択肢と閉じるの画面内表示']});await ctx.close();}
fs.writeFileSync(path.join(__dirname,'creation-v120'+(process.argv.includes('--release')?'-release':'')+'.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
