'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const E=require(require('node:fs').existsSync(require('node:path').join(__dirname,'../dist/script.js'))?'../dist/script.js':'../script.js'),R=E.R,D=E.D,U=require(require('node:fs').existsSync(require('node:path').join(__dirname,'../dist/driving-ui.js'))?'../dist/driving-ui.js':'../driving-ui.js'),G=require(require('node:fs').existsSync(require('node:path').join(__dirname,'../dist/race-renderer.js'))?'../dist/race-renderer.js':'../race-renderer.js');
const results=[];let assertions=0;const ok=(x,msg)=>{assertions++;assert.ok(x,msg);},eq=(a,b,msg)=>{assertions++;assert.deepEqual(a,b,msg);};
function test(name,fn){try{fn();results.push({name,passed:true});console.log('PASS',name);}catch(e){results.push({name,passed:false,error:e.stack});console.log('FAIL',name,e.message);}}
function career(seed=501){const s=E.newState(seed);E.createCareer(s,E.character(s,'操船テスト'));E.startSeries(s);E.prepareRace(s);s.career.status='race';const r=s.career.series.race;E.startDrive(s.career,r);return {s,r,d:r.drive};}
function fixture(seed=312,base=45,rough=false){const c={seed};const list=Array.from({length:6},(_,i)=>{const p=E.character(c,'艇'+i,base);D.statKeys.forEach(k=>p.stats[k]=E.clamp(p.stats[k],0,100));p.equipment=E.equipment(c);return p;});return E.makeRace(c,list,D.venues[rough?3:0],{weather:rough?'雨':'晴れ',wind:rough?'横風':'無風',windSpeed:rough?10:0},'qualifier',list[0].id);}
function pilotToGoal(r,d){d.paused=false;let ticks=0;while(!d.finished&&ticks++<(R.C.timeLimit+R.C.prestart+1)*60)R.tick(d,r,R.pilot(d,R.own(d),r));ok(d.finished,'must finish or DNF');}
test('端数を保持し表示だけ切り下げ、ランク境界を維持',()=>{eq(R.display(49.99),'49 D');eq(R.display(50),'50 C');eq(R.display(89.99),'89 A');eq(R.display(90),'90 S');eq(R.display(100),'100 S');const {s}=career();const c=s.career;c.player.stats.turn=49.9;c.status='action';const before=c.player.stats.turn;const t=E.train(c,'turn');ok(c.player.stats.turn%1!==0);const delta=R.floor(c.player.stats.turn)-R.floor(before);ok(t.text.includes('＋'+delta+' → '+R.display(c.player.stats.turn)));ok(!/\d\.\d/.test(t.text));['boat','motor','prop'].forEach(p=>Object.entries(c.player.equipment[p]).forEach(([k,v])=>ok(/[-+]?\d+ [SABCDE]$/.test(R.display(v,R.equipmentRange(p,k),true)))));});
test('反時計回りの幾何と全周の投影が一致',()=>{const start=R.pointAt(R.C.start),next=R.pointAt(R.C.start+1);ok(next.x>start.x);const right=R.pointAt(2*R.C.halfStraight+Math.PI*R.C.radius/2);ok(right.x>R.C.halfStraight&&Math.abs(right.z)<1e-6);ok(right.heading<0);for(let i=0;i<200;i++){const s=R.C.length*i/200,p=R.pointAt(s);ok(Math.abs(R.wrap((R.project(p.x,p.z).s-s)/R.C.length*Math.PI*2))<1e-7);}});
test('助走中、入力なしでは自動前進せず、アクセルで物理移動',()=>{const r=fixture(),d=R.create(r,501);d.paused=false;const start=R.own(d).x;for(let i=0;i<120;i++)R.tick(d,r,{});const b=R.own(d);ok(Math.abs(b.x-start)<.2);for(let i=0;i<150;i++)R.tick(d,r,{throttle:1});ok(b.speed>2);ok(b.x>start+3);ok(d.countdown>0);});
test('有効スタート後に左へ操舵でき、アクセルを離すと減速',()=>{const r=fixture(),d=R.create(r,702);d.paused=false;for(let i=0;i<660;i++)R.tick(d,r,R.pilot(d,R.own(d),r));const b=R.own(d),old=b.heading,speed=b.speed;ok(!b.startFault);for(let i=0;i<60;i++)R.tick(d,r,{steer:-.7,throttle:0});ok(R.wrap(b.heading-old)<-.03);ok(b.speed<speed);});
test('安定系スキル・旋回能力が実際のグリップを改善',()=>{const r=fixture(),d=R.create(r,6),b=R.own(d),base=R.performance(b,d,r);b.effects.push({id:'steady',stats:{turn:5},safety:.38,until:6});const active=R.performance(b,d,r);ok(active.grip>base.grip);ok(active.wave<=base.wave);b.effects=[];b.stats.turn+=15;ok(R.performance(b,d,r).grip>base.grip);});
test('セッティングと機材・環境が物理性能に反映',()=>{const r=fixture(),d=R.create(r,6),b=R.own(d),base=R.performance(b,d,r);r.strategy='safe';ok(R.performance(b,d,r).grip>base.grip);ok(R.performance(b,d,r).topSpeed<base.topSpeed);r.strategy='attack';ok(R.performance(b,d,r).topSpeed>base.topSpeed);r.strategy='balanced';b.equipment.motor.speed+=10;ok(R.performance(b,d,r).topSpeed>base.topSpeed);r.env={weather:'雨',wind:'横風',windSpeed:10};ok(R.performance(b,d,r).wave>base.wave);});
test('保存と復元後、同一入力は同一の位置・速度・抽選になる',()=>{const {s,r,d}=career(702);d.paused=false;for(let i=0;i<1200;i++)R.tick(d,r,R.pilot(d,R.own(d),r));const restored=E.decode(JSON.stringify(s)),r2=restored.career.series.race;for(let i=0;i<800;i++){const command=R.pilot(d,R.own(d),r);R.tick(d,r,command);const restoredCommand=R.pilot(r2.drive,R.own(r2.drive),r2);eq(command,restoredCommand);R.tick(r2.drive,r2,restoredCommand);}eq(d,r2.drive);ok(E.validState(s));});
test('30 / 60 / 120fpsで固定60Hzの走行結果が一致',()=>{const r=fixture(),runs=[];for(const hz of [30,60,120]){const d=R.create(r,551);d.paused=false;let acc=0;for(let frame=0;frame<hz*20;frame++){acc+=1/hz;while(acc>=R.DT-1e-10){R.tick(d,r,R.pilot(d,R.own(d),r));acc-=R.DT;}}runs.push(d);}eq(runs[0],runs[1]);eq(runs[1],runs[2]);});
test('一時停止と立て直しで位置・順位の進行を水増ししない',()=>{const {r,d}=career();d.paused=false;for(let i=0;i<720;i++)R.tick(d,r,R.pilot(d,R.own(d),r));d.paused=true;const copy=E.clone(d);R.tick(d,r,{throttle:1});eq(d,copy);const b=R.own(d),progress=b.progress;ok(R.rescue(d));eq(b.progress,progress);eq(b.penaltyUntil,d.elapsed+4);d.paused=false;for(let i=0;i<180;i++)R.tick(d,r,{throttle:1});eq(b.progress,progress);eq(b.metrics.rescues,1);});
test('逆走は進行距離を増やさず、3周前にゴールしない',()=>{const r=fixture(),d=R.create(r,19),b=R.own(d);d.paused=false;d.countdown=0;d.started=true;d.elapsed=12;b.startTime=.25;b.heading=Math.PI;for(let i=0;i<180;i++)R.tick(d,r,{throttle:1});ok(b.progress<0);eq(b.finishTime,null);eq(b.checkpoints,0);});
test('実走のゴール順で賞金とポイント、二重清算を防止',()=>{const {s,r,d}=career(61);pilotToGoal(r,d);E.completeDrive(s);const z=s.career.lastResult;eq(z.finish.map(n=>n.id),R.ranks(d).map(b=>b.id));eq(z.place,R.place(d,R.own(d)));ok(z.driving.time>0);ok(E.validState(s));const money=s.career.player.money;E.completeDrive(s);eq(s.career.player.money,money);E.continueAfterRace(s);eq(s.career.series.round,1);eq(s.career.status,'action');ok(E.validState(s));});
test('制限時間でリタイア、転覆と区別して0pt・0賞金',()=>{const {s,r,d}=career(910);d.paused=false;d.countdown=0;d.started=true;d.elapsed=R.C.timeLimit+R.C.prestart-.05;R.own(d).startTime=.25;while(!d.finished)R.tick(d,r,{});E.completeDrive(s);ok(s.career.lastResult.dnf);eq(s.career.lastResult.capsized,false);eq(s.career.lastResult.points,0);eq(s.career.lastResult.money,0);ok(E.validState(s));});
test('転覆地点は固定され、完走艇より後ろに並ぶ',()=>{const r=fixture(123),d=R.create(r,19),b=R.own(d);d.countdown=0;d.started=true;d.paused=false;d.elapsed=12;d.boats.forEach(n=>n.startTime=.25);b.stress=3;const p=R.pointAt(130);b.x=p.x;b.z=p.z;b.progress=130-R.C.start;b.lastS=130;R.tick(d,r,{throttle:1,steer:-1});ok(b.capsized);const pos={x:b.x,z:b.z,progress:b.progress};R.finishOthers(d,r);eq({x:b.x,z:b.z,progress:b.progress},pos);eq(R.ranks(d).at(-1).id,b.id);});
test('妨害の50%・完全反射は再反射しない',()=>{for(const [guard,factor] of [['immune',0],['reflect',.5],['mirror',1]]){let seen=false;for(let seed=1;seed<40&&!seen;seed++){const r=fixture(seed);r.runners.forEach((n,i)=>n.skills=i===0?['start_check','mirror']:[guard]);const d=R.create(r,seed);d.countdown=0;d.paused=false;R.tick(d,r,{throttle:1});const attacks=d.events.filter(e=>e.kind==='debuff');if(!attacks.length)continue;seen=true;eq(attacks.length,1);eq(attacks[0].reflected,attacks[0].amount*factor);ok(attacks[0].blocked);ok(d.events.some(e=>e.abilityId===guard));}ok(seen);}});
test('高レア発動イベントに能力ID・艇番・時間が直接入る',()=>{const r=fixture();r.runners[0].skills=['legend_start'];let seen=false;for(let seed=1;seed<20&&!seen;seed++){const d=R.create(r,seed);d.countdown=0;d.paused=false;R.tick(d,r,{});const ev=d.events.find(e=>e.abilityId==='legend_start');if(ev){seen=true;eq(ev.rarity,'LR');eq(ev.frame,r.runners[0].frame);ok(Number.isFinite(ev.t));}}ok(seen);});
test('旧v70セーブの育成を維持、未完了レースだけ再スタート',()=>{const {s,r}=career();delete r.drive;s.version=70;E.advance(s.career,r);const stats=E.clone(s.career.player.stats),restored=E.decode(JSON.stringify(s));eq(restored.version,80);eq(restored.career.player.stats,stats);eq(restored.career.series.race.phase,-1);eq(restored.career.series.race.done,false);ok(E.validState(restored));});
test('壊れた走行JSON・能力ID・描画座標を拒否',()=>{const {s}=career();for(const mutate of [d=>d.boats[0].x=1e100,d=>d.boats[0].skills=['unknown'],d=>d.boats[0].equipment.motor.speed='x',d=>d.boats[0].frame=99,d=>d.controls.steer=100,d=>d.events=[{kind:'ability',abilityId:'bad'}]]){const bad=E.clone(s);mutate(bad.career.series.race.drive);assertions++;assert.throws(()=>E.decode(JSON.stringify(bad)));}});
test('登録選手レースも任意の1艇を操船、原本は成長しない',()=>{const s=E.newState(812);s.registry=Array.from({length:6},(_,i)=>E.character(s,'登録'+i));const original=E.clone(s.registry),ids=s.registry.map(n=>n.id),q=E.quickRace(s,ids,null,0,ids[4]);eq(q.race.runners.find(n=>n.isPlayer).id,ids[4]);E.startDrive(s,q.race);pilotToGoal(q.race,q.race.drive);E.completeDrive(s,true);ok(q.paid);eq(s.registry,original);ok(E.validState(s));});
test('左右操舵範囲とミニマップの番号配置が有界',()=>{const rect={left:20,width:160};eq(U.steerFromPointer(100,rect),0);eq(U.steerFromPointer(0,rect),-1);eq(U.steerFromPointer(300,rect),1);const r=fixture(),d=R.create(r,72);d.boats.forEach((b,i)=>{const p=R.pointAt(144+i*.1);b.x=p.x;b.z=p.z;});const labels=U.mapLabels(d);eq(new Set(labels.map(l=>l.x+':'+l.y)).size,6);labels.forEach(l=>ok(l.x>=8&&l.x<=192&&l.y>=9&&l.y<=115));});
test('3Dジオメトリ・視点行列が有限、前方の物体を投影できる',()=>{[G.boxMesh(),G.hullMesh(),G.coneMesh(),G.planeMesh(10,4),G.ringMesh(21,63)].forEach(m=>{ok(m.length%18===0);ok(m.every(Number.isFinite));});const vp=G.multiply(G.perspective(Math.PI/2,1,.1,600),G.lookAt([0,1,0],[10,1,0],[0,1,0]));const v=[10,1,0,1],clip=[0,0,0,0];for(let i=0;i<4;i++)for(let k=0;k<4;k++)clip[i]+=vp[k*4+i]*v[k];ok(clip[3]>0);ok(Math.abs(clip[0])<1e-6);ok(Math.abs(clip[1])<1e-6);});
const ai=[];
test('新人〜SG相当・晴天/強風で全6艇が3周を完走',()=>{for(const base of [40,70,95])for(const rough of [false,true])for(const seed of [91,212]){const r=fixture(seed,base,rough),d=R.runAI(r,seed);eq(d.boats.filter(b=>b.finishTime!==null).length,6);d.boats.forEach(b=>{eq(b.checkpoints,24);eq(b.progress,R.C.goal);});ai.push({base,weather:rough?'雨・横風10':'晴れ・無風',seed,finishes:R.ranks(d).map(b=>({frame:b.frame,seconds:Math.round(b.finishTime*100)/100,contacts:b.metrics.contacts,boundaries:b.metrics.boundaries}))});}});
test('実走から全9シリーズの終了・登録へ到達（SG条件は検証用に充足）',()=>{const s=E.newState(4312);E.createCareer(s,E.character(s,'全季試走'));let races=0,guard=0;while(s.career&&guard++<800){const c=s.career;if(c.status==='home'){if(c.stage===8)c.player.totalEarnings=Math.max(1800,c.player.totalEarnings);E.startSeries(s);}else if(['seriesIntro','between'].includes(c.status))E.prepareRace(s);else if(c.status==='action'){E.train(c,'turn');c.status='race';E.startDrive(c,c.series.race);pilotToGoal(c.series.race,c.series.race.drive);E.completeDrive(s);races++;ok(E.validState(s));}else if(c.status==='raceResult')E.continueAfterRace(s);else if(c.status==='seriesResult'){if(c.stage===7&&c.ending==='gate'){c.player.totalEarnings=1800;c.ending=null;c.lastShop=null;}if(c.stage<8)E.nextSeries(s);else{eq(c.history.length,9);ok(races>=45&&races<=54);E.register(s);}}else throw Error('unexpected '+c.status);}eq(s.career,null);eq(s.registry.length,1);ok(E.validState(s));});
const report={assertions,passed:results.filter(r=>r.passed).length,failed:results.filter(r=>!r.passed).length,results,ai,browser_tested:false,android_device_tested:false};
fs.writeFileSync(path.join(__dirname,'driving-results.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({assertions,passed:report.passed,failed:report.failed}));if(report.failed)process.exitCode=1;
