'use strict';
// Real drawing commands and HUD/event functions. No browser layout or physical-device claim.
const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('node:assert/strict');
const {createCanvas}=require('@napi-rs/canvas');
const E=require('../src/script'),R=E.R,UI=require('../src/driving-ui'),Renderer=require('../src/race-renderer');
const report={build:'126',scope:'Real Canvas overlay + real driving HUD/input with a DOM event adapter; not browser/device verification',checks:[]};
function test(name,fn){fn();report.checks.push(name)}
function fixture(){const s=E.newState(124),p=E.character(s,'検証選手');p.scenario='light';const c=E.createCareer(s,p);E.startSeries(s);E.prepareRace(s);const r=c.series.race;r.drive=R.create(r,124);return r;}
function paint(levels,motion=true,quality='full',time=16.5){const ops=[],ctx={clearRect(...v){ops.push(['clear',...v])},beginPath(){},moveTo(...v){ops.push(['move',...v])},lineTo(...v){ops.push(['line',...v])},stroke(){ops.push(['stroke',this.strokeStyle,this.lineWidth])}};const count=UI.paintWeather(ctx,393,852,levels,time,motion,quality);return {count,ops};}
const spray={rain:0,wind:0,speed:0,spray:1,rough:1,side:1};
test('晴天でも航走による飛沫が出て、速度と風波・引き波で増す',()=>{const r=fixture(),b=R.own(r.drive);r.env={weather:'晴',wind:'無風',windSpeed:0};r.venue.roughness=0;b.speed=0;b.wakeLoad=0;assert.equal(UI.effectLevels(r.drive,r).spray,0);b.speed=12;const slow=UI.effectLevels(r.drive,r);b.speed=23;const fast=UI.effectLevels(r.drive,r);assert.equal(fast.rain,0);assert.ok(fast.spray>slow.spray&&slow.spray>0);b.wakeLoad=.7;const wake=UI.effectLevels(r.drive,r);assert.ok(wake.spray>fast.spray);r.env.windSpeed=9;r.venue.roughness=.8;const rough=UI.effectLevels(r.drive,r);assert.ok(rough.spray>wake.spray);assert.ok(paint({...rough,wind:0,speed:0}).count>0)});
test('飛沫は短命の決定的な軌跡で中央視界を避ける',()=>{const a=paint(spray),b=paint(spray,true,'full',16.57);assert.deepEqual(a,paint(spray));assert.notDeepEqual(a.ops,b.ops);assert.ok(a.count>12&&a.count<=26);for(const op of a.ops.filter(x=>x[0]==='move')){assert.ok(op[1]<393*.24||op[1]>393*.76);assert.ok(op[2]>852*.58)}assert.ok(a.ops.every(o=>o.every(v=>typeof v!=='number'||Number.isFinite(v))))});
test('演出控えめは飛沫を減らし、演出なし・動き停止は描かない',()=>{assert.ok(paint(spray,true,'soft').count<paint(spray).count);assert.equal(paint(spray,false).count,0);assert.equal(paint(spray,true,'off').count,0);assert.equal(paint(spray,false,'soft').ops.length,1)});
test('粒子は半透明で微小、中心部の実ピクセルも完全透明',()=>{const c=createCanvas(393,852),ctx=c.getContext('2d');UI.paintWeather(ctx,393,852,spray,16.5,true,'full');const px=ctx.getImageData(0,0,393,852).data;let visible=0,max=0;for(let y=0;y<852;y++)for(let x=0;x<393;x++){const alpha=px[(y*393+x)*4+3];if(alpha){visible++;max=Math.max(max,alpha);assert.ok(x<393*.24||x>393*.76)}}assert.ok(visible>0&&visible<393*852*.012);assert.ok(max<120);report.sprayPixels={visible,total:393*852,maxAlpha:max};});
test('天候と飛沫描画は状態・乱数を変更しない',()=>{const r=fixture(),b=R.own(r.drive);r.env.weather='雨';b.speed=23;b.wakeLoad=.6;const before=JSON.stringify(r),random=Math.random;Math.random=()=>{throw Error('game RNG must not be used by visual overlay')};try{for(const quality of['full','soft','off'])for(const t of[0,1.3,17.4,90])paint(UI.effectLevels(r.drive,r),true,quality,t);}finally{Math.random=random}assert.equal(JSON.stringify(r),before)});
function target(){const listeners={};return {listeners,addEventListener(t,f){(listeners[t]??=[]).push(f)},removeEventListener(t,f){listeners[t]=(listeners[t]||[]).filter(x=>x!==f)},emit(t,e={}){for(const f of[...(listeners[t]||[])])f({preventDefault(){},...e})},classList:{add(){},remove(){},toggle(){}},style:{},dataset:{},hidden:true,innerHTML:'',textContent:'',clientWidth:393,clientHeight:852,setAttribute(){},getBoundingClientRect(){return{width:160,height:140,left:0,top:0}},setPointerCapture(){},getContext(){return null}}}
function mount(r=fixture(),settings={}){const nodes={},get=id=>nodes[id]??=(target()),doc=target();doc.hidden=false;doc.getElementById=get;get('modal').hidden=true;const effects=createCanvas(393,852),effectContext=effects.getContext('2d');get('weather-fx').getContext=()=>effectContext;let nextFrame,now=0,saves=0;const eventRoot=target(),context={...eventRoot,console,document:doc,PointerEvent:function(){},performance:{now:()=>now},requestAnimationFrame:f=>(nextFrame=f,1),cancelAnimationFrame(){},setTimeout:()=>1,matchMedia:()=>({matches:false}),KM_RACING:R,KM_DATA:E.D,KM_THRILL:require('../src/thrill'),KM_FEEDBACK:require('../src/race-feedback'),KM_RACE_RENDERER:{COLORS:Renderer.COLORS,freshCanvas:x=>x,create:canvas=>({canvas,mode:'canvas',draw(){},project:()=>null,isLost:()=>false,destroy(){}})}};
vm.createContext(context);vm.runInContext(fs.readFileSync(path.join(__dirname,'../src/driving-ui.js'),'utf8'),context);const controller=context.KM_DRIVE_UI.mount(r,{motion:true,renderMode:'canvas',...settings},{save(){saves++},finish(){},skip(){},exit(){}});return{r,controller,doc,get,root:context,effects,saves:()=>saves,step(ms=17){now+=ms;nextFrame(now)},resume(){get('drive-shell').emit('click',{target:{closest:()=>({dataset:{drive:'resume'}})}})}};}
test('スタート待機HUDは直進・踏み始めの案内だけで許容秒を表示しない',()=>{const q=mount(),hud=q.get('start-readout').innerHTML;assert.match(hud,/通過まで直進のみ/);assert.match(hud,/踏み始めは色帯が目安/);assert.doesNotMatch(hud,/許容|\d|秒|実質/);q.controller.destroy()});
test('A以上とB以下の判定説明は閉じたTips、旧許容式は表示しない',()=>{const q=mount(),html=q.get('drive-overlay').innerHTML,tips=html.match(/<details class="drive-start-tips">([\s\S]*?)<\/details>/);assert.ok(tips);assert.match(tips[1],/特殊能力がある場合は例外/);assert.match(tips[1],/A以上/);assert.match(tips[1],/B以下は時計が頂点に戻る前の通過でフライング/);assert.doesNotMatch(tips[1],/\d|0\.002|0\.20|許容.*秒/);assert.doesNotMatch(html,/能力×|早発許容|最速表示/);q.controller.destroy()});
test('実際に通過したSTとF判定は維持する',()=>{for(const fault of[null,'F']){const r=fixture(),b=R.own(r.drive);b.startTime=fault?-.03:.13;b.startFault=fault;r.drive.elapsed=R.startAt(r.drive)+.5;const q=mount(r);assert.ok(q.get('start-readout').innerHTML.includes(fault||'ST '+R.startText(.13)));q.controller.destroy()}});
test('操舵と加速は別ポインターで継続し、指を離せば解除される',()=>{const q=mount();q.resume();q.get('steer-pad').emit('pointerdown',{pointerId:10,clientX:30,clientY:70});q.get('steer-pad').emit('pointermove',{pointerId:10,clientX:100,clientY:70});q.get('throttle-pedal').emit('pointerdown',{pointerId:20,clientX:300,clientY:700});q.step();q.step();assert.equal(q.r.drive.controls.throttle,1);assert.ok(q.r.drive.controls.steer>0);q.root.emit('pointerup',{pointerId:20});q.step();assert.equal(q.r.drive.controls.throttle,0);assert.ok(q.r.drive.controls.steer>0);q.get('steer-pad').emit('lostpointercapture',{pointerId:10});q.step();assert.equal(q.r.drive.controls.steer,0);q.controller.destroy()});
test('非表示・画面回転で保持入力を解除し、復帰しても自動再開しない',()=>{const q=mount();q.resume();q.root.emit('keydown',{key:'w'});q.step();q.step();assert.equal(q.r.drive.controls.throttle,1);const saves=q.saves(),elapsed=q.r.drive.elapsed;q.root.emit('blur');q.doc.hidden=true;q.doc.emit('visibilitychange');q.root.emit('pagehide');q.root.emit('orientationchange');assert.equal(q.saves(),saves+1);assert.equal(q.r.drive.paused,true);assert.equal(q.r.drive.controls.throttle,0);q.step(10000);assert.equal(q.r.drive.elapsed,elapsed);q.doc.hidden=false;q.doc.emit('visibilitychange');assert.equal(q.r.drive.paused,true);q.controller.destroy()});
test('一時停止では重ね描きの飛沫を消し、再開時だけ描く',()=>{
 const r=fixture(),b=R.own(r.drive);b.speed=23;b.vx=Math.cos(b.heading)*23;b.vz=Math.sin(b.heading)*23;b.startTime=.1;r.env.weather='晴れ';r.drive.elapsed=17;
 const q=mount(r),alpha=()=>q.effects.getContext('2d').getImageData(0,0,393,852).data.some((v,i)=>i%4===3&&v>0);
 q.step(40);assert.equal(alpha(),false);q.resume();q.step(40);q.step(40);assert.equal(alpha(),true);
 q.root.emit('keydown',{key:'Escape'});q.step(40);assert.equal(r.drive.paused,true);assert.equal(alpha(),false);q.controller.destroy();
});
test('演出なしと揺れOFFは実際の描画ループでも重ね描きしない',()=>{for(const settings of [{raceFX:'off'},{motion:false}]){const r=fixture();R.own(r.drive).speed=23;r.env.weather='雨';const q=mount(r,settings);q.resume();q.step(40);q.step(40);assert.ok(q.effects.getContext('2d').getImageData(0,0,393,852).data.every(x=>x===0));q.controller.destroy();}});
fs.writeFileSync(path.join(__dirname,'drive-ui-v126.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
