'use strict';
const assert=require('node:assert/strict');
const E=require(require('fs').existsSync(require('path').join(__dirname,'../dist/script.js'))?'../dist/script.js':'../script.js'),D=E.D;
const results=[];let assertions=0;
function check(name,fn){try{fn();results.push({name,passed:true});console.log('PASS '+name);}catch(e){results.push({name,passed:false,error:e.stack});console.error('FAIL '+name+'\n'+e.stack);}}
function ok(x,msg){assertions++;assert.ok(x,msg);}
function eq(x,y,msg){assertions++;assert.deepEqual(x,y,msg);}
function career(seed=101){const s=E.newState(seed);E.createCareer(s,E.character(s,'検証選手'));return s;}
function begin(s){ok(E.startSeries(s));ok(E.prepareRace(s));}
function run(s,mode='training',restore=false){const c=s.career;let safety=0;
  while(c.status!=='seriesResult'&&c.status!=='registration'){
    if(++safety>100)throw Error('state loop '+c.status);
    if(c.status==='home'){E.startSeries(s);continue;}
    if(c.status==='seriesIntro'||c.status==='between'){E.prepareRace(s);continue;}
    if(c.status==='action'){
      const g=E.growthOf(c.player).values;const target=D.statKeys.slice().sort((a,b)=>c.player.stats[a]/g[a]-c.player.stats[b]/g[b])[0];
      if(mode==='tuning')E.tune(c,'motor');else if(mode==='mixed'&&c.series.round%2===0)E.tune(c,c.series.round%4===0?'motor':'prop');else E.train(c,target);
      c.status='preRace';
    }
    if(c.status==='preRace')c.status='race';
    if(c.status==='race'){while(!c.series.race.done){E.advance(c,c.series.race,null);ok(E.validState(s),'invalid during race');}E.settleRace(s);}
    if(c.status==='raceResult'){ok(E.validState(s),'invalid result');E.continueAfterRace(s);}
  }
  ok(E.validState(s),'invalid series result');return c.history.at(-1);
}
check('全能力ID・レア度・カテゴリ・タグと効果データが整合',()=>{eq(new Set(D.abilities.map(a=>a.id)).size,D.abilities.length);D.abilities.forEach(a=>{ok(D.rarities.includes(a.rarity));ok(D.categories.includes(a.category));ok(a.tags.includes(a.category));ok(a.chance>=0&&a.chance<=1);ok(a.phases.every(n=>n>=0&&n<=4));});D.rarities.forEach(r=>ok(D.abilities.some(a=>a.rarity===r&&a.category!=='弱点')));});
check('予選の全20名が5走・報酬の二重適用なし',()=>{const s=career();begin(s);const c=s.career;for(let k=0;k<5;k++){const r=c.series.race;E.simulate(c,r);const z=E.settleRace(s);const amount=c.player.money;eq(E.settleRace(s),null);eq(c.player.money,amount);[c.player,...c.series.npcs].forEach(n=>eq(n.finishes.reduce((a,b)=>a+b,0),k+1));if(k<4)E.continueAfterRace(s);}eq(c.series.round,5);});
check('JSON復元で同じ次フェーズ・同じ抽選結果',()=>{const s=career(23);begin(s);E.train(s.career,'turn');s.career.status='race';E.advance(s.career,s.career.series.race);const restored=E.decode(JSON.stringify(s));E.advance(s.career,s.career.series.race,'sashi');E.advance(restored.career,restored.career.series.race,'sashi');eq(s,restored);});
check('調整成長1→0.55→0.22、練習でリセット。機材幅は同一乱数で維持',()=>{const s=career(241);begin(s);const c=s.career;const gains=[];for(let k=0;k<3;k++){c.series.action.normal=1;const res=E.tune(c,'motor');gains.push(res.diminish);}eq(gains,[1,.55,.22]);c.series.action.normal=1;E.train(c,'power');eq(c.balance,{last:null,streak:0});c.series.action.normal=1;eq(E.tune(c,'motor').diminish,1);const x=E.clone(c),y=E.clone(c);x.series.action.normal=y.series.action.normal=1;x.balance={last:null,streak:0};y.balance={last:'motor',streak:3};eq(E.tune(x,'prop').changes,E.tune(y,'prop').changes);});
check('行動回数制限・通常練習は次走補正なし・機材持続',()=>{const s=career();begin(s);const c=s.career;ok(E.train(c,'speed'));eq(E.train(c,'turn'),null);ok(E.tune(c,'motor'));eq(E.tune(c,'prop'),null);eq(c.series.race.buff.speed,0);const eqp=E.clone(c.player.equipment);E.simulate(c,c.series.race);E.settleRace(s);E.continueAfterRace(s);eq(c.series.race.buff,E.clone(Object.fromEntries(D.statKeys.map(k=>[k,0]))));eq(c.player.equipment,eqp);});
check('追加行動券は1走1枚・枠指定・成長型変更・弱点克服',()=>{const s=career();begin(s);const c=s.career;c.player.inventory={training:2,tune:1,lane:1,boost:1,growth:1,cure:1};const orig=c.player.growth;E.useItem(c,'growth');ok(c.player.growth!==orig);c.player.skills.push('weak_start');E.useItem(c,'cure','weak_start');ok(!c.player.skills.includes('weak_start'));E.useItem(c,'training');eq(c.series.action.training,2);ok(E.useItem(c,'training').error);E.useItem(c,'lane');eq(c.series.race.runners.find(n=>n.isPlayer).frame,1);E.useItem(c,'boost');eq(c.series.race.itemBoost,5);ok(E.validState(s));});
check('SG進出1800万円の境界・累計は買い物で減らない',()=>{const s=career(),c=s.career;c.stage=8;c.player.totalEarnings=1799.9;eq(E.startSeries(s),false);eq(c.ending,'gate');c.status='home';c.ending=null;c.player.totalEarnings=1800;ok(E.startSeries(s));c.stage=6;c.status='home';c.player.money=20000;c.player.totalEarnings=30000;c.shop=E.generateShop(c);const id=c.shop.stock[0].id;ok(!E.buySkill(c,id).error);eq(c.player.totalEarnings,30000);});
check('招待選手はSG優勝戦のみ・登録名を維持・最大2人',()=>{const s=career(71);const c=s.career;const record=E.character(s,'歴代の王者',86);record.skills=['legend_speed'];s.registry.push(record);const rival=E.character(s,'記憶の好敵手',88);rival.skills=['reflect'];s.rivals.push(rival);c.stage=8;c.player.totalEarnings=2000;begin(s);ok(!c.series.npcs.some(p=>p.id===record.id||p.id===rival.id));ok(!c.series.race.runners.some(p=>p.special));c.series.round=5;c.status='between';c.player.points=50;c.series.npcs.forEach((p,i)=>p.points=40-i);E.prepareRace(s);eq(c.series.finalType,'championship');const sp=c.series.race.runners.filter(n=>n.special);eq(sp.length,2);eq(sp.map(n=>n.name).sort(),['歴代の王者','記憶の好敵手'].sort());});
check('SG優勝LR確定・招待選手先着報酬・重複は習熟',()=>{const s=career(719),c=s.career;const record=E.character(s,'歴代選手',90);record.skills=['legend_speed'];s.registry.push(record);c.stage=8;c.player.totalEarnings=2000;begin(s);c.series.round=5;c.status='between';c.player.points=50;c.series.npcs.forEach((n,i)=>n.points=40-i);E.prepareRace(s);const r=c.series.race;E.simulate(c,r);r.runners.forEach(n=>{n.capsized=false;n.score=n.isPlayer?10000:1;});const z=E.settleRace(s);eq(z.place,1);ok(z.acquired.some(a=>a.source==='SG優勝報酬'&&D.abilityMap[a.id].rarity==='LR'));ok(z.acquired.some(a=>a.source==='歴代選手に先着'));E.continueAfterRace(s);eq(c.ending,'sgChampion');const id=c.player.skills[0],old=c.player.mastery[id]||1;E.acquire(c,c.player,id,'test');eq(c.player.mastery[id],old+1);});
check('弱点の通常抽選・ショップ除外、ラストショップ1回制限',()=>{const s=career(888),c=s.career;c.stage=6;c.player.money=30000;c.ending='gate';c.lastShop=E.generateShop(c,true);eq(c.lastShop.stock.length,5);c.lastShop.stock.forEach(a=>{ok(D.abilityMap[a.id].rarity!=='LR');ok(D.abilityMap[a.id].category!=='弱点');});ok(!E.buySkill(c,c.lastShop.stock[0].id,true).error);ok(E.buySkill(c,c.lastShop.stock[1].id,true).error);});
check('妨害耐性・50%反射・完全反射が再反射しない',()=>{
  for(const [defense,factor] of [['immune',0],['reflect',.5],['mirror',1]]){
    let found=false;for(let seed=1;seed<40&&!found;seed++){
      const c={seed};const p=Array.from({length:6},(_,i)=>{const n=E.character(c,'艇'+i);n.equipment=E.equipment(c);n.skills=i===0?['start_check','mirror']:[defense];return n;});
      const r=E.makeRace(c,p,D.venues[0],{weather:'晴れ',wind:'無風',windSpeed:0});E.advance(c,r);
      const attacks=r.events.filter(e=>e.kind==='debuff');if(!attacks.length)continue;found=true;eq(attacks.length,1);ok(attacks[0].blocked);eq(attacks[0].reflected,attacks[0].amount*factor);
      const source=r.runners.find(n=>n.id===attacks[0].from);if(factor)ok(source.phaseHistory[0].debuff<0);else eq(source.phaseHistory[0].debuff,0);
    }ok(found,'debuff did not activate');
  }
});
check('カットインは発動IDを保持・フェーズ更新で古い対象を削除',()=>{const s=career(178);begin(s);const c=s.career,r=c.series.race;r.runners[0].skills=['legend_start','legend_speed'];let seen=false;while(!r.done){E.advance(c,r);r.cutins.forEach(e=>{ok(e.abilityId&&D.abilityMap[e.abilityId]);eq(e.phase,r.phase);if(e.rarity==='LR')seen=true;});}ok(seen);});
check('転覆艇の進行停止・最後尾・0pt/0賞金',()=>{const s=career(84);begin(s);const c=s.career,r=c.series.race;E.advance(c,r);const n=r.runners.find(n=>n.isPlayer);n.capsized=true;n.capsizePhase=1;const progress=n.progress;E.simulate(c,r);eq(n.progress,progress);eq(E.ordered(r).at(-1).id,n.id);const z=E.settleRace(s);eq(z.points,0);eq(z.money,0);});
check('任意6人の作成選手レース・コイン一度だけ清算',()=>{const s=career(661);s.registry=Array.from({length:6},(_,i)=>E.character(s,'登録'+i));const records=E.clone(s.registry),ids=s.registry.map(n=>n.id);const q=E.quickRace(s,ids,ids[0],100);eq(s.coins,900);E.simulate(s,q.race);q.race.runners.forEach(n=>{n.capsized=false;n.score=n.id===ids[0]?99999:1;});E.payQuick(s);eq(s.coins,1200);E.payQuick(s);eq(s.coins,1200);eq(s.registry,records);ok(E.validState(s));ok(E.quickRace(s,[...ids.slice(0,5),ids[0]]).error);});
check('全9シリーズ完走と未達終了の双方を通過',()=>{const s=career(506),c=s.career;for(let stage=0;stage<9;stage++){eq(c.stage,stage);if(stage===7){c.player.totalEarnings=1800;c.player.money=1800;}run(s,'mixed');if(stage<8)ok(E.nextSeries(s));}ok(['sgChampion','sgFinished'].includes(c.ending));eq(c.history.length,9);const record=E.register(s);ok(record);eq(s.career,null);eq(s.registry.length,1);const t=career(567);t.career.stage=7;t.career.player.stats=Object.fromEntries(D.statKeys.map(k=>[k,0]));run(t);eq(t.career.ending,'gate');eq(E.nextSeries(t),false);});
check('破損・旧版・不正ID・不正人数JSONを拒否',()=>{const s=career();begin(s);const cases=[{},Object.assign(E.clone(s),{version:31}),E.clone(s),E.clone(s),E.clone(s)];cases[2].career.player.skills=['<script>'];cases[3].career.series.race.runners.pop();cases[4].career.player.stats.speed=-10;const injected=E.clone(s);injected.career.player.id='x" onmouseover=alert(1)';cases.push(injected);const broken=E.clone(s);broken.career.player.points='<img>';cases.push(broken);cases.forEach(x=>assert.throws(()=>E.decode(JSON.stringify(x))));eq(E.decode(JSON.stringify(s)),s);});
check('実際の転覆はターン地点に固定され、その後動かない',()=>{let found=false;for(let seed=1;seed<=120&&!found;seed++){const c={seed};const list=Array.from({length:6},(_,i)=>{const p=E.character(c,'低能力'+i);p.stats=Object.fromEntries(D.statKeys.map(k=>[k,12]));p.equipment=E.equipment(c);return p;});const r=E.makeRace(c,list,D.venues[3],{weather:'雨',wind:'横風',windSpeed:10},'qualifier',list[0].id);r.strategy='attack';E.advance(c,r);E.advance(c,r,'outside');const n=r.runners.find(n=>n.capsized);if(n){found=true;ok(n.progress>.2);const fixed=n.progress;E.simulate(c,r);eq(n.progress,fixed);}}ok(found);});
check('6着で弱点獲得、1着で克服の実抽選が作動',()=>{let gained=false,cured=false;for(let seed=1;seed<100&&(!gained||!cured);seed++){const s=career(seed*931);begin(s);const c=s.career,r=c.series.race;const own=r.runners.find(n=>n.isPlayer);if(!gained){E.simulate(c,r);r.runners.forEach(n=>{n.capsized=false;n.score=n.isPlayer?-1000:1000;});const z=E.settleRace(s);if(z.weakness.gained){gained=true;ok(c.player.skills.includes(z.weakness.gained));}}else{c.player.skills.push('weak_start');E.simulate(c,r);r.runners.forEach(n=>{n.capsized=false;n.score=n.isPlayer?10000:1;});const z=E.settleRace(s);if(z.weakness.cured){cured=true;ok(!c.player.skills.includes(z.weakness.cured));}}}ok(gained);ok(cured);});
check('弱点武器化の高レアIDをカットインへ渡す',()=>{let seen=false;for(let seed=1;seed<30&&!seen;seed++){const s=career(seed);begin(s);const c=s.career,r=c.series.race,n=r.runners.find(n=>n.isPlayer);n.skills=['weak_start','comeback'];E.advance(c,r);if(r.cutins.some(e=>e.abilityId==='comeback')){seen=true;ok(n.phaseHistory[0].skill>0);}}ok(seen);});
check('カットインや補正値が不正なJSONを拒否',()=>{const s=career();begin(s);s.career.status='race';E.advance(s.career,s.career.series.race);const bad=E.clone(s);bad.career.series.race.cutins=[{abilityId:'unknown',frame:1,phase:0,name:'test'}];assert.throws(()=>E.decode(JSON.stringify(bad)));const bad2=E.clone(s);bad2.career.series.race.venue.stats.speed='invalid';assert.throws(()=>E.decode(JSON.stringify(bad2)));});
check('保存拒否・容量超過時にメモリへ退避し、既読データを保持',()=>{const blocked=E.createSafeStorage(()=>{throw Error('denied');},'test');eq(blocked.persistent,false);blocked.set('save','abc');eq(blocked.get('save'),'abc');blocked.remove('save');eq(blocked.get('save'),null);let fail=false;const store={save:'old'};const disk={setItem(k,v){if(fail)throw Error('quota');store[k]=v;},getItem(k){if(fail)throw Error('blocked');return store[k]??null;},removeItem(k){delete store[k];}};const safe=E.createSafeStorage(()=>disk,'test');eq(safe.persistent,true);eq(safe.get('save'),'old');fail=true;eq(safe.get('save'),'old');eq(safe.persistent,false);safe.set('save','new');eq(safe.get('save'),'new');eq(store.save,'old');});
console.log(JSON.stringify({assertions,passed:results.filter(x=>x.passed).length,failed:results.filter(x=>!x.passed).length},null,2));
if(process.argv.includes('--json'))require('fs').writeFileSync(require('path').join(__dirname,'engine-results.json'),JSON.stringify({assertions,results},null,2));
if(results.some(x=>!x.passed))process.exitCode=1;
