'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const E=require('../src/script'),R=E.R,clone=structuredClone;
const report={checks:[],startRuns:[],wakeMatrix:[]};
function check(name,fn){fn();report.checks.push(name);}
function near(a,b,t=1e-9){assert.ok(Math.abs(a-b)<=t,`${a} != ${b}`);}
function fixture(seed=124){const s=E.newState(seed),p=E.character(s,'物理検証');p.scenario='light';const c=E.createCareer(s,p);E.startSeries(s);E.prepareRace(s);const r=c.series.race;r.venue.stats={};r.env={weather:'晴',wind:'無風',windSpeed:0};r.tilt=0;r.controlMode='manual';r.startPolicy='attack';for(const b of r.runners){b.skills=[];b.mastery={};b.racePersona=null;b.stats=Object.fromEntries(E.D.statKeys.map(k=>[k,50]));}const d=R.create(r,seed,{keepCourses:true});r.drive=d;return {s,c,r,d,b:R.own(d)};}
function crossing(stat,seconds,extra={}){const {r,d,b}=fixture();Object.assign(b,extra);b.stats.start=stat;const line=R.pointAt(R.C.start).x;b.x=line-3.5+.01;d.elapsed=R.startAt(d)+seconds+R.DT/2;R.startCrossing(d,b,line-.01,R.DT);return {r,d,b};}
check('C 以下は早発余裕ゼロ、B 以上は従来式。表示ランクと 65 境界が一致',()=>{for(const v of [0,1,34,50,64,64.9999,65,65.0001,80,90,100,120]){const b={stats:{start:v}};near(R.startAllowance(b),v<65?0:Math.min(v,100)*.002);if(v<65)assert.notEqual(R.gradeValue(v).rank,'B');else if(v<80)assert.equal(R.gradeValue(v).rank,'B');}});
check('C の負 ST は F、0 秒は合法。数値計算の丸め境界に耐える',()=>{for(const stat of [0,50,64.9999]){for(const t of [-.12,-.001,-.0000002])assert.equal(crossing(stat,t).b.startFault,'F');for(const t of [-5e-8,0,5e-8,.01])assert.equal(crossing(stat,t).b.startFault,null);assert.equal(crossing(stat,0).b.startTime,0);}});
check('B 以上の許容境界は合法、境界の明確な超過は F、L 判定は維持',()=>{for(const stat of [65,80,100,120]){const allowance=Math.min(stat,100)*.002;for(const t of [-allowance,-allowance+5e-8])assert.equal(crossing(stat,t).b.startFault,null);assert.equal(crossing(stat,-allowance-.000001).b.startFault,'F');assert.equal(crossing(stat,1.499).b.startFault,null);assert.equal(crossing(stat,1.5).b.startFault,'L');}});
const specials=[{id:'cast_kagura',castId:'kagura',castRole:'boss',racePersona:'wall_start'},{id:'cast_teiou',castRole:'king',racePersona:'king'},{id:'main_izumi',racePersona:'rival_final'}];
check('強敵も C 以下は例外なし。B 以上だけ既存の先駆スタートを維持',()=>{for(const special of specials){for(const stat of [50,64.9999,65,100,120]){const b={...special,isPlayer:false,stats:{start:stat},aiBias:1};assert.equal(R.earlyStart(b),stat>=65);near(R.startAllowance(b),stat>=65?.3:0);const crossed=crossing(stat,-.3,{...special,isPlayer:false}).b;assert.equal(crossed.startFault,stat>=65?null:'F');}assert.equal(R.earlyStart({...special,isPlayer:true,stats:{start:100}}),false);}});
check('攻め/安全の目標は C 以下で 0 秒前を狙わず、一時バフは資格を変更しない',()=>{const {r,d,b}=fixture();for(const policy of ['safe','attack'])for(const stat of [0,30,50,64.999,65,80,100]){r.startPolicy=policy;b.stats.start=stat;const target=R.startTarget(b,r);assert.ok(target>=-R.startAllowance(b));if(stat<65)assert.ok(target>0);}b.stats.start=64;b.statsBuff.start=20;assert.equal(R.startAllowance(b),0);b.stats.start=65;b.effects.push({id:'dash',stats:{start:-20},until:99,safety:0,kind:'debuff',mechanics:{}});near(R.startAllowance(b),.13);});
check('新規レースの目標は初期化済み。旧途中セーブの目標だけを更新し、判定は遡及しない',()=>{const {r,d,b}=fixture();assert.ok(b.startAim>0);d.paused=false;d.elapsed=1;d.frame=60;b.startAim=-.2;const already=d.boats.find(n=>n!==b);already.startTime=-.10;already.startFault=null;already.startAim=-.18;const seed=d.seed;for(const n of d.boats)n.lastZone='0';R.tick(d,r,{throttle:0});assert.ok(b.startAim>0);near(already.startTime,-.10);assert.equal(already.startFault,null);near(already.startAim,-.18);assert.equal(d.seed,seed);});
check('途中セーブの再開は旧 startAim 値が違っていても同じ位置・乱数・判定へ進む',()=>{const {r,d}=fixture();d.paused=false;for(let i=0;i<240;i++)R.tick(d,r,{},R.DT,true);const a=clone(d),b=clone(d);for(const n of a.boats)n.startAim=-.3;for(const n of b.boats)n.startAim=0;for(let i=0;i<480;i++){R.tick(a,r,{},R.DT,true);R.tick(b,r,{},R.DT,true);}assert.deepEqual(a,b);assert.ok(a.boats.every(n=>n.startTime===null||n.startFault===null));});
for(const policy of ['safe','attack'])check('C 以下の実助走は F を起こさず通過する: '+policy,()=>{for(const stat of [0,30,50,64.999]){const {r,d,b}=fixture(100+stat|0);r.startPolicy=policy;for(const n of d.boats)n.stats.start=stat;d.paused=false;while(d.elapsed<13.49)R.tick(d,r,{},R.DT,true);for(const n of d.boats){assert.equal(n.startFault,null,`${policy}/${stat}/${n.course}`);assert.ok(n.startTime>=0,`${policy}/${stat}/${n.course}: ${n.startTime}`);}report.startRuns.push({policy,start:stat,ST:d.boats.map(n=>+n.startTime.toFixed(6))});}});
check('生能力 65 以上の強敵は実助走で従来通り先行、C は通常の合法通過',()=>{for(const stat of [50,65,100]){const {r,d}=fixture();const b=d.boats[1];Object.assign(b,specials[1]);b.stats.start=stat;d.paused=false;while(d.elapsed<13.49)R.tick(d,r,{},R.DT,true);assert.equal(b.startFault,null);if(stat<65)assert.ok(b.startTime>=0);else near(b.startTime,-.30,.0001);}});
check('フィジカル発波・受波の差は 50 を基準に両端 ±8%、0〜120 で連続・単調',()=>{let last=null;for(let power=0;power<=120;power+=.25){const q=R.physicalWake(power);assert.ok(q.emission>=.92-1e-12&&q.emission<=1.08+1e-12);assert.ok(1-q.resistance>=.644-1e-12&&1-q.resistance<=.756+1e-12);if(last){assert.ok(q.emission<=last.emission+1e-12);assert.ok(q.resistance>=last.resistance-1e-12);assert.ok(Math.abs(q.emission-last.emission)<.001);}last=q;}for(const [power,emitted,received] of [[0,1.08,.756],[50,1,.70],[100,.92,.644],[120,.92,.644]]){const q=R.physicalWake(power);near(q.emission,emitted);near(1-q.resistance,received);}});
check('実際の performance は有効フィジカルを使い、低い艇は強く受け・強く後ろに残す',()=>{const {r,d,b}=fixture();let prev=null;for(const power of [0,20,50,80,100,120]){b.stats.power=power;const p=R.performance(b,d,r);near(p.wakeEmission,R.physicalWake(power).emission);near(p.wakeResistance,R.physicalWake(power).resistance);if(prev){assert.ok(p.wakeEmission<=prev.wakeEmission);assert.ok(p.wakeResistance>=prev.wakeResistance);}prev=p;}b.stats.power=40;b.statsBuff.power=10;near(R.performance(b,d,r).wakeEmission,1);near(R.performance(b,d,r).wakeResistance,.30);});
check('引き波耐性スキルと上限は維持され、発波スキルも消さない',()=>{const {r,d,b}=fixture();b.stats.power=50;const base=R.performance(b,d,r);b.effects=[{id:'wave',stats:{},until:100,safety:0,kind:'buff',mechanics:{wakeShield:.45}}];const shield=R.performance(b,d,r);near(shield.wakeResistance,base.wakeResistance+.45);b.effects.push({id:'steady',stats:{},until:100,safety:.5,kind:'buff',mechanics:{wakeShield:.4}});near(R.performance(b,d,r).wakeResistance,.88);b.effects=[{id:'comet',stats:{},until:100,safety:0,kind:'buff',mechanics:{wakeEmit:.65}}];const emitted=R.performance(b,d,r);near(R.wakeStrength(20,emitted),1.65);b.stats.power=0;near(R.wakeStrength(20,R.performance(b,d,r)),1.65*1.08);b.stats.power=100;near(R.wakeStrength(20,R.performance(b,d,r)),1.65*.92);near(R.wakeStrength(100,R.performance(b,d,r)),2);});
check('同速の発波 × 受波の組合せも基準の約 ±17% 以内。低能力同士で過大に増えない',()=>{const neutral=.70;for(const front of [0,50,100,120])for(const rear of [0,50,100,120]){const a=R.physicalWake(front),b=R.physicalWake(rear),load=a.emission*(1-b.resistance),ratio=load/neutral;assert.ok(ratio>=.8464-1e-9&&ratio<=1.1664+1e-9);report.wakeMatrix.push({front,rear,load:+load.toFixed(6),neutralRatio:+ratio.toFixed(6)});}});
check('保存される引き波は上限内で、残っている旧波へ倍率を二重適用しない',()=>{const {r,d,b}=fixture();d.elapsed=20;b.x=0;b.z=40;b.startTime=0;d.wakes=[{owner:d.boats[1].id,x:0,z:37.2,fx:1,fz:0,t:19,strength:1.2}];const before=clone(d.wakes),a=R.sampleWake(d,b);b.stats.power=0;const low=R.sampleWake(d,b);b.stats.power=100;const high=R.sampleWake(d,b);assert.deepEqual(a,low);assert.deepEqual(a,high);assert.deepEqual(d.wakes,before);assert.ok(a.strength>0&&a.strength<=2);});
report.passed=report.checks.length;
fs.writeFileSync(path.join(__dirname,'physics-v124.json'),JSON.stringify(report,null,2));
console.log(JSON.stringify({passed:report.passed,startRuns:report.startRuns.length,wakeMatrix:report.wakeMatrix.length}));
