const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const E=require('../src/script'),Craft=require('../src/craft118'),P=require('../src/practice122'),R=E.R;
const clone=x=>structuredClone(x),report={build:'124',checks:[],actualDrills:[]};
function test(name,fn){fn();report.checks.push(name);}
function trial(kind='turn',seed=118){const t=Craft.practice(E,kind,undefined,seed);R.own(t.r.drive).stats.start=65;t.initial=clone(t.r);return t;}
function complete(t,values={}){const d=t.r.drive,b=R.own(d);d.elapsed=t.initial.drive.elapsed+(values.time??15);d.finished=true;d.paused=true;b.progress=t.r.practiceLimit;b.startTime=values.st??.08;b.startFault=null;b.capsized=false;b.dnf=false;b.speed=(values.exitSpeed??65)/3.6;Object.assign(b.metrics,{slideSeconds:values.slideSeconds??3,contacts:values.contacts??2,boundaries:values.boundaries??1,wakeSeconds:values.wakeSeconds??4});return t;}
test('比較処理は育成・乱数・入力オブジェクトを変更しない',()=>{const s=E.newState(122),p=E.character(s,'検証選手');p.scenario='light';E.createCareer(s,p);const before=JSON.stringify(s),t=Craft.practice(E,'turn',p);t.initial=clone(t.r);complete(t);const original=JSON.stringify(t);let store=null;for(let i=0;i<5;i++){const old=JSON.stringify(store);P.compare(store,t);P.history(store,t);P.sanitize(store);assert.equal(JSON.stringify(store),old);store=P.record(store,t).store;}assert.equal(JSON.stringify(t),original);assert.equal(JSON.stringify(s),before);assert.equal(s.practice,undefined);});
test('初回記録は前回なし・項目別ベストを作る',()=>{const t=complete(trial()),z=P.record(null,t);assert.equal(z.comparison.previous,null);assert.equal(z.comparison.first,true);assert.equal(z.comparison.attempts,1);assert.deepEqual(z.comparison.personalBests,P.metrics('turn').map(x=>x.id));assert.equal(z.comparison.best.time,15);assert.equal(z.comparison.best.exitSpeed,65);assert.equal(z.store.groups.length,1);});
test('前回と自己ベストを方向付きの指標で比較する',()=>{const t=complete(trial());const first=P.record(null,t),u=complete(trial(),{time:13,exitSpeed:70,slideSeconds:1,contacts:1,boundaries:0}),z=P.record(first.store,u);assert.equal(z.comparison.previous.metrics.time,15);assert.equal(z.comparison.deltas.previous.time,-2);assert.equal(z.comparison.deltas.previous.exitSpeed,5);assert.equal(z.comparison.bestBefore.time,15);assert.equal(z.comparison.best.time,13);assert.ok(z.comparison.personalBests.includes('contacts'));assert.equal(P.metrics('turn').find(x=>x.id==='exitSpeed').better,'higher');assert.equal(P.metrics('turn').find(x=>x.id==='contacts').better,'lower');});
test('自己ベストは項目別で保持し、悪化で上書きしない',()=>{let store=P.record(null,complete(trial(),{time:13,exitSpeed:60,contacts:0})).store;const z=P.record(store,complete(trial(),{time:16,exitSpeed:72,contacts:3}));assert.equal(z.comparison.best.time,13);assert.equal(z.comparison.best.exitSpeed,72);assert.equal(z.comparison.best.contacts,0);assert.equal(z.comparison.deltas.best.time,3);assert.ok(!z.comparison.personalBests.includes('time'));});
test('早発許容内の負のSTを保持し、より早い合法STを改善とする',()=>{const first=P.record(null,complete(trial('start'),{st:.04})),next=P.record(first.store,complete(trial('start'),{st:-.08}));assert.equal(next.comparison.current.status,'complete');assert.equal(next.comparison.best.st,-.08);assert.equal(next.comparison.deltas.previous.st,-.12);const a=complete(trial('start'),{st:-.11});assert.equal(P.record(next.store,a).comparison.best.st,-.11);});
test('F・L・転覆・DNF・時間切れ・未完了はベストに入らない',()=>{const old=P.record(null,complete(trial())).store;for(const status of ['F','L','capsized','dnf','timeout','unfinished']){const t=complete(trial(),{time:1,exitSpeed:99,slideSeconds:0,contacts:0,boundaries:0}),b=R.own(t.r.drive);if(status==='F'||status==='L'){b.startFault=status;b.dnf=true;}if(status==='capsized')b.capsized=true;if(status==='dnf')b.dnf=true;if(status==='timeout'){t.r.drive.elapsed=79;b.progress=t.r.practiceLimit-1;}if(status==='unfinished')t.r.drive.finished=false;const z=P.record(old,t);assert.equal(z.comparison.current.completed,false,status);assert.deepEqual(z.comparison.best,old.groups[0].best,status);assert.deepEqual(z.comparison.personalBests,[],status);assert.ok(Object.values(z.comparison.deltas.previous).every(x=>x===null),status);}});
test('Fフラグ欠落でも許容超過STを誤って合法記録にしない',()=>{const t=complete(trial('start'),{st:-.131});assert.equal(P.summarize(t).status,'F');assert.equal(P.record(null,t).comparison.best,null);const late=complete(trial('start'),{st:1.5});assert.equal(P.summarize(late).status,'L');assert.equal(P.record(null,late).comparison.best,null);});
test('未完了の前回は表示するが改善値は作らない',()=>{const t=trial('wake');t.r.drive.finished=true;t.r.drive.elapsed+=66;const old=P.record(null,t).store,z=P.record(old,complete(trial('wake')));assert.equal(z.comparison.previous.status,'unfinished');assert.ok(Object.values(z.comparison.deltas.previous).every(v=>v===null));assert.equal(z.comparison.best.wakeSeconds,4);});
test('同じ条件の再作成・キー順・名前・可変ID・時刻に影響されない',()=>{const t=trial(),u=trial(),key=P.conditionKey(t);u.initial.id='changed-race-id';u.initial.savedAt=12345;u.initial.createdAt=56789;u.initial.drive.replay.frames=[];u.initial.drive.logs.push({text:'different log'});for(const b of u.initial.drive.boats){b.name='別の表示名';b.id='renamed-'+b.frame;b.portraitKey='different';b.updatedAt=888;b.stats=Object.fromEntries(Object.entries(b.stats).reverse());}assert.equal(P.conditionKey(u),key);complete(t);assert.equal(P.conditionKey(t),key);});
test('能力・装備・技・熟練度・水面・コース・チルト・難度・方針を混ぜない',()=>{const t=trial(),key=P.conditionKey(t),mutations=[
 u=>R.own(u.initial.drive).stats.speed++,u=>R.own(u.initial.drive).equipment.motor.condition--,
 u=>R.own(u.initial.drive).skills.push('test_skill'),u=>R.own(u.initial.drive).mastery.test_skill=2,
 u=>u.initial.env.weather='雨',u=>u.initial.env.windSpeed=5,u=>u.initial.venue.roughness+=.1,
 u=>{const a=u.initial.drive.boats;[a[0].course,a[1].course]=[a[1].course,a[0].course];},
 u=>u.initial.tilt=1.5,u=>u.initial.difficulty='easy',u=>u.initial.startPolicy='attack',
 u=>u.initial.practiceLimit++,u=>u.initial.drive.seed++,u=>u.initial.drive.boats[1].x+=.01,
 u=>R.own(u.initial.drive).posture=1,u=>u.initial.drive.boats[1].stats.power++
 ];for(const mutate of mutations){const u=clone(t);mutate(u);assert.ok(P.conditionKey(u));assert.notEqual(P.conditionKey(u),key);}assert.notEqual(P.conditionKey(trial('wake')),key);});
test('変化後の能力・条件は初回として扱う',()=>{const t=complete(trial()),old=P.record(null,t).store,u=complete(trial());R.own(u.initial.drive).stats.accel++;R.own(u.r.drive).stats.accel++;const z=P.record(old,u);assert.equal(z.comparison.previous,null);assert.equal(z.comparison.first,true);assert.equal(z.store.groups.length,2);});
test('姿勢補助を一度でも使用した記録は完全手動と比較しない',()=>{const t=complete(trial()),old=P.record(null,t).store,assisted=clone(t);assisted.assistUsed=true;assert.notEqual(P.conditionKey(t),P.conditionKey(assisted));const z=P.record(old,assisted);assert.equal(z.comparison.previous,null);assert.equal(z.store.groups.length,2);const again=clone(assisted);again.practiceSettings={postureAssist:false};assert.equal(P.conditionKey(again),P.conditionKey(assisted));assert.equal(P.compare(z.store,again).previous.completed,true);});
test('区間の初期値を引いた時間と接触・横滑り・引き波を記録する',()=>{const t=trial();Object.assign(R.own(t.initial.drive).metrics,{contacts:2,boundaries:1,slideSeconds:3,wakeSeconds:2});complete(t,{time:12,contacts:5,boundaries:4,slideSeconds:7,wakeSeconds:8});const m=P.summarize(t).metrics;assert.equal(m.time,12);assert.equal(m.contacts,3);assert.equal(m.boundaries,3);assert.equal(m.slideSeconds,4);assert.equal(m.wakeSeconds,6);});
test('最大12条件・直近3回に収まり、過去のベストは残る',()=>{let store=P.record(null,complete(trial(),{time:4,contacts:0})).store;for(let i=0;i<10;i++)store=P.record(store,complete(trial(),{time:10+i,contacts:4})).store;assert.equal(store.groups[0].attempts.length,3);assert.equal(store.groups[0].total,11);assert.equal(store.groups[0].best.time,4);for(let i=0;i<20;i++){const t=complete(trial());t.initial.tilt=i/10;store=P.record(store,t).store;}assert.equal(store.groups.length,12);assert.ok(store.groups.every(g=>g.attempts.length<=3));report.historyBytes=Buffer.byteLength(JSON.stringify(store));assert.ok(report.historyBytes<150000);});
test('履歴をJSON保存して再読込しても前回・ベストが等しい',()=>{const t=complete(trial('wake')),z=P.record(null,t),raw=JSON.stringify(z.store);assert.deepEqual(P.sanitize(JSON.parse(raw)),z.store);assert.deepEqual(P.history(JSON.parse(raw),t),z.store.groups[0]);assert.deepEqual(P.compare(JSON.parse(raw),t),P.compare(z.store,t));});
test('壊れた履歴・未知版・不正値を安全に除去する',()=>{for(const raw of [null,undefined,0,'x',[],{}, {version:4,groups:[]},{version:1,groups:[null,5,{}, {kind:'turn',key:'p122:bad',attempts:[]}]}])assert.deepEqual(P.sanitize(raw),{version:1,groups:[]});const t=complete(trial('start')),z=P.record(null,t).store,g=z.groups[0];g.best.st=-10;g.attempts[0].metrics.st=-10;assert.deepEqual(P.sanitize(z),{version:1,groups:[]});const w=P.record(null,complete(trial())).store;w.groups[0].attempts.push({kind:'turn',completed:true,status:'F',metrics:{time:-1}});w.groups[0].best.time=Infinity;const clean=P.sanitize(w);assert.equal(clean.groups[0].attempts.length,1);assert.equal(clean.groups[0].best.time,15);for(const invalid of [null,{}, {kind:'turn',r:{}},{kind:'unknown'}]){assert.equal(P.conditionKey(invalid),null);assert.equal(P.compare(w,invalid),null);assert.equal(P.record(w,invalid).comparison,null);}});
test('3種類とも実際の物理更新で終了し、記録から比較できる',()=>{for(const kind of ['start','turn','wake']){const t=trial(kind),d=t.r.drive;d.paused=false;let ticks=0;while(!d.finished&&ticks++<5000){R.tick(d,t.r,R.pilot(d,R.own(d),t.r));const b=R.own(d);if(b.startFault||b.capsized||b.dnf||b.progress>=t.r.practiceLimit||R.raceTime(d)>(kind==='start'?12:65)){d.finished=true;d.paused=true;}}const z=P.record(null,t);assert.equal(z.comparison.current.completed,true,kind);assert.ok(z.comparison.best);const identical=clone(t);assert.ok(Object.values(P.compare(z.store,identical).deltas.previous).every(v=>Math.abs(v)<1e-7));report.actualDrills.push({kind,ticks,status:z.comparison.current.status,metrics:z.comparison.current.metrics});}});

test('旧走行ルールで合法だったC能力の練習記録を残し、新ルールとは比較しない',()=>{const fixture=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/practice-v123.json'),'utf8')),before=JSON.stringify(fixture.store);assert.deepEqual(P.sanitize(fixture.store),fixture.store);assert.equal(JSON.stringify(fixture.store),before);assert.equal(JSON.parse(fixture.store.groups[0].key.slice(5)).revision,1);const t=complete(trial('start'),{st:.08});assert.equal(JSON.parse(P.conditionKey(t).slice(5)).revision,2);const next=P.record(fixture.store,t);assert.equal(next.comparison.previous,null);assert.equal(next.comparison.first,true);assert.equal(next.store.groups.length,2);assert.equal(next.store.groups[0].attempts[0].metrics.st,-.08);assert.equal(P.summarize(fixture.trial).status,'F');});
test('C以下の負のSTは新しい練習ベストに入らず、ゼロは有効',()=>{const t=complete(trial('start'),{st:-.001});R.own(t.r.drive).stats.start=R.own(t.initial.drive).stats.start=64;assert.equal(P.summarize(t).status,'F');assert.equal(P.record(null,t).comparison.best,null);R.own(t.r.drive).startTime=0;assert.equal(P.summarize(t).status,'complete');assert.equal(P.record(null,t).comparison.best.st,0);});

fs.writeFileSync(path.join(__dirname,'practice-v124.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
