const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),E=require('../src/script'),Dialog=require('../src/dialogue');
const report={layouts:[],interactions:[],faces:[],errors:[]},screens=path.join(__dirname,'../work120/screens');fs.mkdirSync(screens,{recursive:true});
const entry=process.argv.includes('--release')?'release-v120/web/index.html':'index.html';
function fixture(last=false){const s=E.newState(120),p=E.character(s,'画面確認');p.scenario='shore';const c=E.createCareer(s,p);Object.assign(c.bonds.heroines.nagi,{met:true,metStage:0,metRace:0});E.Bonds.open(c,'nagi');const sc=E.Bonds.scene(c);if(last)c.development.readers[Dialog.bookmark('bond:'+sc.key)]=Dialog.pages(sc.body).length-1;assert.ok(E.validState(s));return s;}
(async()=>{
 const browser=await chromium.launch({executablePath:'/workspace/scratch/7e276fc3919e/pw-browsers/chromium_headless_shell-1161/chrome-linux/headless_shell',headless:true,args:['--no-sandbox']}),ctx=await browser.newContext({viewport:{width:360,height:640},isMobile:true,hasTouch:true}),page=await ctx.newPage();page.on('pageerror',e=>report.errors.push(e.message));
 async function boot(s){await page.goto('http://127.0.0.1:8765/'+entry);await page.waitForFunction(()=>!!window.KM_APP);await page.evaluate(raw=>localStorage.setItem('kyotei_monogatari_v80',raw),JSON.stringify(s));await page.reload();await page.waitForFunction(()=>!!window.KM_APP);await page.addStyleTag({content:"@font-face{font-family:QAJP;src:url('/tests/qa-japanese.otf')}body,button,input,select{font-family:QAJP,sans-serif!important}"});await page.evaluate(()=>document.fonts.ready);await page.locator('[data-action=resume]').first().click();}
 await boot(fixture());await page.locator('[data-action=bonds]').first().click();const index=async()=>Number((await page.locator('.novel-tools>span').innerText()).split('/')[0]);assert.equal(await index(),1);
 await page.touchscreen.tap(20,150);assert.equal(await index(),2);await page.locator('.novel-cast').tap();assert.equal(await index(),3);await page.locator('.novel-box').tap();assert.equal(await index(),4);report.interactions.push('背景・人物・本文で一回ずつ進行');
 await page.mouse.move(30,160);await page.mouse.down();await page.mouse.move(80,200,{steps:5});await page.mouse.up();assert.equal(await index(),4);report.interactions.push('スワイプで進行しない');
 await page.locator('[data-action=novelHistory]').click();assert.equal(await index(),4);await page.locator('button[data-action=closeModal]').click();assert.equal(await index(),4);
 await page.locator('.sound-controls summary').click();assert.equal(await index(),4);await page.locator('.sound-controls summary').click();await page.locator('[data-action=novelPrev]').click();assert.equal(await index(),3);report.interactions.push('履歴・音量・前へは本文タップに波及しない');
 await page.locator('[data-action=novelExit]').click();assert.equal(await page.locator('.novel-stage').count(),0);await page.locator('[data-action=meet][data-value=nagi]').click();assert.equal(await index(),3);report.interactions.push('閉じると再開のしおりを維持');
 // Use the longest authored reply-page text and longest authored labels, including large type.
 const chapters=E.Bonds.B.heroines.flatMap(h=>[...h.chapters,...(h.recoveryChapters||[])]),longest=chapters.map(ch=>Dialog.parse(Dialog.pages(ch.body).at(-1)).text).sort((a,b)=>b.length-a.length)[0],labels=chapters.flatMap(ch=>ch.choices.map(x=>x.label)).sort((a,b)=>b.length-a.length).slice(0,3);
 for(const [width,height]of [[320,568],[360,640],[360,740],[393,852],[768,1024]])for(const large of [false,true]){
  await page.setViewportSize({width,height});const s=fixture(true);s.settings.textSize=large?'large':'normal';await boot(s);await page.locator('[data-action=bonds]').first().click();
  await page.evaluate(({longest,labels})=>{document.querySelector('.novel-text').textContent=longest;document.querySelectorAll('.novel-choice b').forEach((n,i)=>n.textContent=labels[i]);}, {longest,labels});
  for(const selector of ['.novel-top h2','.novel-close','.novel-box','.novel-choices']){const b=await page.locator(selector).boundingBox();assert.ok(b.x>=-1&&b.x+b.width<=width+1&&b.y>=0&&b.y+b.height<=height+1,selector+JSON.stringify({width,height,large,b}));}
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert.equal(await page.locator('.novel-bottom').evaluate(el=>el.scrollHeight<=el.clientHeight+1),true,JSON.stringify({width,height,large,metrics:await page.locator('.novel-bottom').evaluate(el=>({scroll:el.scrollHeight,client:el.clientHeight,box:el.getBoundingClientRect().toJSON(),header:document.querySelector('.novel-top').getBoundingClientRect().toJSON()}))}));
  for(const n of await page.locator('.novel-choice').all())assert.ok((await n.boundingBox()).height>=44);
  await page.screenshot({path:path.join(screens,`reader-${width}-${height}-${large?'large':'normal'}.png`)});report.layouts.push({width,height,large,allChoicesVisible:true});
 }
 const before=await page.evaluate(()=>JSON.stringify(KM_APP.getState().career.bonds));await page.touchscreen.tap(20,170);assert.equal(await page.evaluate(()=>JSON.stringify(KM_APP.getState().career.bonds)),before);assert.equal(await page.locator('.novel-choices').count(),1);await page.locator('[data-action=bondChoice]').nth(1).click();assert.equal(await page.evaluate(()=>KM_APP.getState().career.bonds.heroines.nagi.step),1);report.interactions.push('返答待ちの背景タップは選ばず、返答を一度だけ反映');
 // Actual campaign UI: 陸 used to fall back to 紗枝. Unknown speakers must not borrow her face.
 const s=fixture();s.career.bonds.pending=null;s.career.campaign.entries[0].prose.body=['陸「最後まで見るよ」','見知らぬ客「こんにちは」','紗枝「おかえり」','相馬「道具を確かめよう」','篠原「音を聞こう」','なつ「応援しているよ」'];await page.setViewportSize({width:360,height:740});await boot(s);await page.locator('[data-action=campaign]').first().click();
 for(const [i,key]of ['riku',null,'rival_12','rival_03','shinohara','natsu'].entries()){
  if(i)await page.touchscreen.tap(20,160);const image=page.locator('.novel-cast .portrait-face');assert.equal(await image.count(),key?1:0);if(key){assert.equal(await image.getAttribute('data-portrait'),key);if(await image.evaluate(n=>n.tagName==='IMG')){await image.evaluate(n=>n.decode());assert.ok(await image.evaluate(n=>n.naturalWidth>0));}}
  report.faces.push({speaker:await page.locator('.novel-speaker').innerText(),key});
 }
 await page.screenshot({path:path.join(screens,'natsu-dedicated-portrait.png')});assert.equal(report.errors.length,0,report.errors.join('\n'));fs.writeFileSync(path.join(__dirname,'reader-v120'+(process.argv.includes('--release')?'-release':'')+'.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
