'use strict';
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),cp=require('node:child_process');
const {createCanvas,loadImage}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/@napi-rs/canvas');
const G=require('../race-renderer'),E=require('../script'),R=E.R,root=path.resolve(__dirname,'..'),out=path.join(root,'previews'),results=[];
const pass=n=>{results.push({name:n,passed:true});console.log('PASS',n);};
function render(name,eye,target,commands,w=960,h=640,weather=[.35,0,0]){const view=G.lookAt(eye,target,[0,1,0]),vp=G.multiply(G.perspective(44*Math.PI/180,w/h,.12,650),view);const data={width:w,height:h,time:32,vertex:G.vertex,fragment:G.fragment,weather,camera:{eye,vp:Array.from(vp)},geometry:G.geometry,commands:[['sphere',Array.from(G.model(...eye,0,480,480,480)),[.725,.898,.937],2],['water',Array.from(G.identity()),[.075,.557,.686],1],...commands],fog:[.725,.898,.937]};const scene=path.join('/tmp','v112-'+name+'-scene.json');fs.writeFileSync(scene,JSON.stringify(data));cp.execFileSync('python3',[path.join(__dirname,'render-webgl.py'),scene,path.join(out,'v112-'+name+'.png')]);}
const emitTo=a=>(k,m,c,v=0)=>a.push([k,Array.from(m),c,v]);
(async()=>{
 for(const key of ['shell','deck','rounded','buoy1','buoy2','buoy3','buoyCollar','buoyBand','digit1']){const a=G.geometry[key];assert.ok(a.length%18===0&&a.every(Number.isFinite));for(let i=0;i<a.length;i+=6)assert.ok(Math.abs(Math.hypot(...a.slice(i+3,i+6))-1)<.0001,key);}
 pass('新しい船体とブイは有限な三角形と単位法線を持つ');
 const base={id:'preview',frame:1,isPlayer:false,x:0,z:0,heading:0,speed:21,steer:0,yawRate:0,heel:0,posture:0},near=[];G.boatScene(base,{elapsed:32},{motion:true},emitTo(near));assert.ok(near.length<100);assert.ok(near.some(x=>x[0]==='digit1'&&x[3]===13));render('boat-close',[5.6,3.35,6.2],[.2,.65,0],near);pass('1号艇の船体と船外機を実GLESで描画');
 const buoy=[];G.buoyScene(0,0,32,{motion:true},emitTo(buoy));render('buoy-close',[5.2,2.5,6],[0,1.25,0],buoy,640,800);pass('水際の襟と赤白の曲面ブイを実GLESで描画');
 // Sample the filled glyph using an independent barycentric point test.
 function covered(x,z){const a=G.geometry.digit1;for(let i=0;i<a.length;i+=18){const p=[0,6,12].map(j=>[a[i+j],a[i+j+2]]);const c=(a,b,c)=>(b[0]-a[0])*(c[1]-a[1])-(b[1]-a[1])*(c[0]-a[0]),q=[x,z],v=[c(p[0],p[1],q),c(p[1],p[2],q),c(p[2],p[0],q)];if(v.every(t=>t>=-1e-8)||v.every(t=>t<=1e-8))return true;}return false;}
 for(let x=-.45;x<.49;x+=.03)assert.ok(covered(x,.04),'1の縦画が途切れない');assert.ok(covered(-.42,-.23)&&covered(-.42,.25));assert.ok(covered(.25,-.20));assert.ok(!covered(0,-.30));pass('数字1の縦画・台座・上端がつながり欠けない');
 const far=[];G.boatScene({...base,x:110},{elapsed:32,boats:[{isPlayer:true,x:0,z:0}]},{lightweight:true},emitTo(far));assert.ok(far.length<near.length/3);pass('遠方では小物を省略し描画量を抑制');
 global.KM_SKY_IMAGE=await loadImage(path.join(root,'assets/shore-panorama.webp'));global.OffscreenCanvas=(function(w,h){return createCanvas(w,h)});
 const s=E.newState(409);E.createCareer(s,E.character(s,'表示検証'));E.startSeries(s);E.prepareRace(s);const r=s.career.series.race,d=E.startDrive(s.career,r);d.elapsed=35;d.started=true;d.paused=false;const player=R.own(d);player.frame=1;
 for(const [i,b] of d.boats.entries()){if(b!==player){const p=R.pointAt(R.C.start+170+i*12,41+i*3);Object.assign(b,p,{progress:170+i*12,frame:i+1});}Object.assign(b,{speed:18,startTime:.1,posture:0});}
 const buoyX=R.C.halfStraight+R.C.inner;Object.assign(player,{x:buoyX-11,z:4.8,heading:-.19,progress:180});
 for(const weather of ['晴れ','雨']){r.env={weather,wind:'横風',windSpeed:weather==='雨'?8:2};const canvas=createCanvas(390,844);canvas.clientWidth=390;canvas.clientHeight=844;const renderer=G.createCanvas(canvas),before=JSON.stringify(d);const start=performance.now();renderer.draw(d,r,{guide:false,motion:true});const ms=performance.now()-start;assert.equal(JSON.stringify(d),before);fs.writeFileSync(path.join(out,'v112-'+(weather==='雨'?'rain':'race')+'-canvas.png'),canvas.toBuffer('image/png'));renderer.destroy();console.log('Canvas first frame ms:',Math.round(ms));
 const cam=G.camera(d,390,844,true),commands=[];G.scene(d,r,{guide:false,motion:true,paintedSky:true},emitTo(commands));const data={width:390,height:844,time:d.elapsed,vertex:G.vertex,fragment:G.fragment,weather:weather==='雨'?[.8,1,0]:[.2,0,0],camera:{eye:cam.eye,vp:Array.from(cam.vp)},geometry:G.geometry,commands:[['sphere',Array.from(G.model(...cam.eye,0,480,480,480)),[.725,.898,.937],2],['water',Array.from(G.identity()),[.075,.557,.686],1],...commands],fog:[.725,.898,.937]};const file='/tmp/v112-race-scene.json';fs.writeFileSync(file,JSON.stringify(data));cp.execFileSync('python3',[path.join(__dirname,'render-webgl.py'),file,path.join(out,'v112-'+(weather==='雨'?'rain':'race')+'-webgl.png')]);assert.equal(JSON.stringify(d),before);pass(weather+'の一人称描画 WebGL/Canvasで物理状態を維持');}
 const own=[];G.boatScene({...base,isPlayer:true},{elapsed:0},{motion:false},emitTo(own));assert.ok(!own.some(x=>['helmet','torso','visor'].includes(x[0])));pass('自艇の頭部を描かず前方視界を確保');
 const a=[],b=[];G.buoyScene(0,0,0,{motion:false},emitTo(a));G.buoyScene(0,0,9,{motion:false},emitTo(b));assert.deepEqual(a,b);pass('演出短縮時はブイの揺れを固定');
 fs.writeFileSync(path.join(__dirname,'render-v112-results.json'),JSON.stringify({build:112,passed:results.length,failed:0,results,method:'Native GLES and Skia Canvas plus geometry tests; not phone performance tests'},null,2));
})().catch(e=>{console.error(e);process.exitCode=1;});
