'use strict';
// Shipped rendering in a real Node Canvas.  This is not a browser/device/FPS test.
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const {createCanvas,loadImage}=require('@napi-rs/canvas'),E=require('../src/script'),R=E.R;
const root=path.resolve(__dirname,'..'),out=path.join(__dirname,'speed-fx-previews');
const UI=require('../src/driving-ui'),T=require('../src/thrill'),report={build:125,scope:'Real Canvas renderer + effects, no browser/HUD/device test',checks:[],frames:[],benchmark:[]};
const check=(name,fn)=>{fn();report.checks.push(name);};
function fixture(weather='晴れ',kmh=84){const {r}=E.Craft.practice(E,'wake',null,125);r.env={weather,wind:'横風',windSpeed:weather==='雨'?7:3};r.drive.elapsed=17.3;r.drive.paused=false;const b=R.own(r.drive);b.speed=kmh/3.6;b.heel=.045;b.wakeLoad=.28;b.posture=-1;r.drive.wakes=[];for(const n of r.drive.boats)for(let i=0;i<7;i++){const fx=Math.cos(n.heading),fz=Math.sin(n.heading),age=i*.22;r.drive.wakes.push({x:n.x-fx*(2.5+i*3.5),z:n.z-fz*(2.5+i*3.5),fx,fz,t:r.drive.elapsed-age,strength:.64});}return r;}
function loadModule(file,key,sky){const context={KM_RACING:R,KM_DATA:E.D,KM_SKY_IMAGE:sky,devicePixelRatio:1,OffscreenCanvas:function(w,h){return createCanvas(w,h)}};vm.createContext(context);vm.runInContext(fs.readFileSync(file,'utf8'),context);return context[key];}
function fxPixels(r,quality='full',motion=true){const c=createCanvas(393,852),ctx=c.getContext('2d');UI.paintWeather(ctx,393,852,UI.effectLevels(r.drive,r),r.drive.elapsed,motion,quality);T.paint(ctx,393,852,{...T.level(r.drive),active:true},r.drive.elapsed,!motion);return ctx.getImageData(0,0,393,852).data;}
(async()=>{
 fs.mkdirSync(out,{recursive:true});const sky=await loadImage(path.join(root,'web/assets/f182808207ebe70798aa.webp'));
 const Renderer=loadModule(path.join(root,'src/race-renderer.js'),'KM_RACE_RENDERER',sky),oldroot=path.join(root,'../v124/src');
 const before={renderer:loadModule(path.join(oldroot,'race-renderer.js'),'KM_RACE_RENDERER',sky),ui:loadModule(path.join(oldroot,'driving-ui.js'),'KM_DRIVE_UI',sky),thrill:loadModule(path.join(oldroot,'thrill.js'),'KM_THRILL',sky)};
 const after={renderer:Renderer,ui:UI,thrill:T};
 check('放射線・ネオン縁・風の集中線を描かない。単独の速度値では画面に線を足さない',()=>{const ctx=createCanvas(393,852).getContext('2d');assert.equal(UI.paintWeather(ctx,393,852,{speed:1,wind:1,spray:0,rain:0},17),0);assert.equal(T.paint(ctx,393,852,{active:true,intensity:1},17),0);assert.ok(ctx.getImageData(0,0,393,852).data.every(x=>x===0));});
 check('晴天時の飛沫は画面下部の外側だけ、中央の操船視界と上部HUD領域は透明',()=>{for(const kmh of [35,55,84,108]){const px=fxPixels(fixture('晴れ',kmh));let count=0;for(let y=0;y<852;y++)for(let x=0;x<393;x++){const a=px[(y*393+x)*4+3];if(a){count++;assert.ok(y>852*.68);assert.ok(x<393*.24||x>393*.76);assert.ok(a<120);}}assert.ok(count<393*852*.01);} });
 check('加速・減速では演出量が連続して増減し、従来の速度境界で点滅しない',()=>{const r=fixture(),b=R.own(r.drive);let last=-1;for(let kmh=0;kmh<=110;kmh+=.025){b.speed=kmh/3.6;const l=UI.effectLevels(r.drive,r),p=Renderer.washProfile(b);assert.ok(l.spray>=last-1e-12);if(last>=0)assert.ok(l.spray-last<.002);assert.ok(p.wash>=0&&p.wash<=.92);last=l.spray;}b.speed=0;assert.equal(UI.effectLevels(r.drive,r).spray,0);assert.equal(Renderer.washProfile(b).wash,0);b.speed=55/3.6;const at=UI.effectLevels(r.drive,r);b.speed=54.999/3.6;assert.ok(Math.abs(at.speed-UI.effectLevels(r.drive,r).speed)<.0001);});
 const wash=(r,settings={motion:true,raceFX:'full'})=>{const ops=[],b=R.own(r.drive);Renderer.hullWashScene(b,r.drive,settings,b,(key,m,color,material=0)=>ops.push({key,m:Array.from(m),color,material}));return ops;};
 check('泡と微細飛沫は艇の座標・旋回方向に追従し、ゲーム乱数を使わない',()=>{const r=fixture(),b=R.own(r.drive),base=wash(r),x=b.x,z=b.z;b.x+=10;b.z-=5;const moved=wash(r);assert.equal(base.length,moved.length);for(let i=0;i<base.length;i++){assert.ok(Math.abs((moved[i].m[12]-base[i].m[12])-10)<1e-5);assert.ok(Math.abs((moved[i].m[14]-base[i].m[14])+5)<1e-5);}b.x=x;b.z=z;const heading=b.heading;b.heading+=Math.PI/2;const turned=wash(r);for(let i=0;i<base.length;i++){const ax=base[i].m[12]-x,az=base[i].m[14]-z;assert.ok(Math.abs(turned[i].m[12]-x+az)<1e-5);assert.ok(Math.abs(turned[i].m[14]-z-ax)<1e-5);}b.heading=heading;const old=Math.random;Math.random=()=>{throw Error('Visual RNG prohibited')};try{assert.deepEqual(wash(r),base);fxPixels(r);}finally{Math.random=old;}});
 check('控えめでは飛沫を削減、演出なし・動き停止では追加の航走演出を停止',()=>{const r=fixture(),full=wash(r),soft=wash(r,{motion:true,raceFX:'soft'}),off=wash(r,{motion:true,raceFX:'off'}),still=wash(r,{motion:false,raceFX:'full'});assert.ok(soft.length<full.length);assert.equal(off.length,5);assert.deepEqual(off,still);assert.ok(fxPixels(r,'off').every(x=>x===0));assert.ok(fxPixels(r,'full',false).every(x=>x===0));});
 check('V124の速度・荒波・フィジカル・姿勢によるカメラは同一',()=>{const r=fixture('雨'),b=R.own(r.drive);for(const speed of [5,15,26])for(const power of [0,50,100])for(const posture of [-1,0,1])for(const motion of [false,true]){b.speed=speed;b.stats.power=power;b.posture=posture;assert.equal(JSON.stringify(Renderer.camera(r.drive,393,852,motion,true,r)),JSON.stringify(before.renderer.camera(r.drive,393,852,motion,true,r)));}});
 function render(api,r,w,h,quality='full'){const c=createCanvas(w,h);c.clientWidth=w;c.clientHeight=h;const renderer=api.renderer.createCanvas(c),saved=JSON.stringify(r);renderer.draw(r.drive,r,{motion:true,raceFX:quality,guide:true});const display=createCanvas(w,h),ctx=display.getContext('2d');ctx.drawImage(c,0,0,w,h);const overlay=createCanvas(w,h),fx=overlay.getContext('2d');api.ui.paintWeather(fx,w,h,api.ui.effectLevels(r.drive,r),r.drive.elapsed,true,quality);if(quality!=='off')api.thrill.paint(fx,w,h,{...api.thrill.level(r.drive),active:true},r.drive.elapsed,quality==='soft');ctx.drawImage(overlay,0,0);assert.equal(JSON.stringify(r),saved);renderer.destroy();return display;}
 for(const [variant,api]of [['v124',before],['v125',after]])for(const weather of ['晴れ','雨'])for(const kmh of [48,84]){const r=fixture(weather,kmh),c=render(api,r,393,852),file=`${variant}-${weather==='雨'?'rain':'sun'}-${kmh}.png`;fs.writeFileSync(path.join(out,file),c.toBuffer('image/png'));report.frames.push({file,kmh,weather,noGameMutation:true,width:393,height:852});}
 const plate=createCanvas(822,934),cx=plate.getContext('2d');cx.fillStyle='#091f2a';cx.fillRect(0,0,822,934);cx.font='bold 19px sans-serif';cx.fillStyle='#e5edef';cx.fillText('V124',16,27);cx.fillText('V125',425,27);cx.font='13px sans-serif';cx.fillStyle='#b2c9cf';cx.fillText('84 km/h / real Canvas rendering, no browser HUD',16,919);for(const [i,v]of ['v124','v125'].entries()){const img=await loadImage(path.join(out,`${v}-sun-84.png`));cx.drawImage(img,16+i*409,43);}fs.writeFileSync(path.join(out,'speed-effects-v125-comparison.png'),plate.toBuffer('image/png'));
 for(const[variant,api]of [['v124',before],['v125',after]])for(const quality of ['full','soft','off']){const r=fixture('雨'),c=createCanvas(393,852);c.clientWidth=393;c.clientHeight=852;const renderer=api.renderer.createCanvas(c),fx=createCanvas(393,852).getContext('2d'),samples=[];for(let i=0;i<9;i++){r.drive.elapsed=17.3+i*.033;const start=performance.now();renderer.draw(r.drive,r,{motion:true,raceFX:quality,guide:true});api.ui.paintWeather(fx,393,852,api.ui.effectLevels(r.drive,r),r.drive.elapsed,true,quality);if(quality!=='off')api.thrill.paint(fx,393,852,{...api.thrill.level(r.drive),active:true},r.drive.elapsed,quality==='soft');if(i>=4)samples.push(performance.now()-start);}samples.sort((a,b)=>a-b);report.benchmark.push({variant,quality,medianMs:+samples[2].toFixed(2),scope:'Node Canvas CPU time, not browser FPS'});renderer.destroy();}
 check('全晴雨・速度の描画でゲーム状態の変更なし',()=>assert.ok(report.frames.every(f=>f.noGameMutation)));
 fs.writeFileSync(path.join(__dirname,'speed-fx-v125.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
})().catch(error=>{console.error(error);process.exitCode=1;});
