'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const E=require('../src/script'),R=E.R,P=require('../src/practice122'),Craft=require('../src/craft118'),clone=structuredClone;
const report={build:'125',checks:[],startRuns:[],oldRecords:[]};
function check(name,fn){fn();report.checks.push(name);}
function near(a,b,t=1e-9){assert.ok(Math.abs(a-b)<=t,`${a} != ${b}`);}
function fixture(seed=125){const s=E.newState(seed),p=E.character(s,'スタート検証');p.scenario='light';const c=E.createCareer(s,p);E.startSeries(s);E.prepareRace(s);const r=c.series.race;r.venue.stats={};r.env={weather:'晴れ',wind:'無風',windSpeed:0};r.tilt=0;r.controlMode='manual';r.startPolicy='attack';for(const b of r.runners){b.skills=[];b.mastery={};b.racePersona=null;b.stats=Object.fromEntries(E.D.statKeys.map(k=>[k,50]));}const d=R.create(r,seed,{keepCourses:true});r.drive=d;return {s,c,r,d,b:R.own(d)};}
function crossing(stat,seconds,extra={}){const {r,d,b}=fixture();Object.assign(b,extra);b.stats.start=stat;const line=R.pointAt(R.C.start).x;b.x=line-3.5+.01;d.elapsed=R.startAt(d)+seconds+R.DT/2;R.startCrossing(d,b,line-.01,R.DT);return {r,d,b};}
check('通常は A 以上に早発余裕。B 以下は 00:00 まで',()=>{for(const [start,expected] of [[0,0],[64,0],[65,0],[79,0],[79.999,0],[80,.16],[90,.18],[100,.20],[120,.20]])near(R.startAllowance({stats:{start},skills:[]}),expected);assert.equal(R.gradeValue(79.999).rank,'B');assert.equal(R.gradeValue(80).rank,'A');});
check('B 以下の負 ST は F、ちょうど 0 秒は有効。丸め誤差と L 境界も確認',()=>{for(const stat of [0,50,65,79.999]){for(const t of [-.16,-.001,-2e-7])assert.equal(crossing(stat,t).b.startFault,'F');for(const t of [-5e-8,0,5e-8,.01,1.499])assert.equal(crossing(stat,t).b.startFault,null);assert.equal(crossing(stat,0).b.startTime,0);assert.equal(crossing(stat,1.5).b.startFault,'L');}});
check('A 以上と所持特能の許容境界は有効、明確な超過は F',()=>{for(const [stat,skills,allowance] of [[80,[],.16],[100,[],.2],[65,['zero'],.06],[79,['legend_start'],.1],[10,['pioneer_start'],.3]]){near(R.startAllowance({stats:{start:stat},skills}),allowance);for(const t of [-allowance,-allowance+5e-8])assert.equal(crossing(stat,t,{skills}).b.startFault,null);assert.equal(crossing(stat,-allowance-.000001,{skills}).b.startFault,'F');}});
check('特能の例外は常時所持かつ最大値を採用。重複・バフ・人物 ID で増幅しない',()=>{for(const isPlayer of [true,false]){const b={isPlayer,stats:{start:70},skills:['zero','legend_start'],statsBuff:{start:30},effects:[{id:'legend_start',stats:{start:31},until:100,mechanics:{}}]};near(R.startAllowance(b),.1);b.skills=['zero','zero'];near(R.startAllowance(b),.06);b.skills=[];near(R.startAllowance(b),0);b.stats.start=80;b.skills=['legend_start'];near(R.startAllowance(b),.16);b.skills.push('pioneer_start');near(R.startAllowance(b),.3);}
 for(const q of [{id:'cast_kagura',castId:'kagura',castRole:'boss'},{id:'cast_teiou',castId:'teiou',castRole:'king'},{id:'main_izumi',racePersona:'rival_final'}]){const b={...q,isPlayer:false,stats:{start:70},skills:[]};near(R.startAllowance(b),0);assert.equal(R.earlyStart(b),false);b.skills=['zero'];assert.equal(R.earlyStart(b),false);b.skills=['pioneer_start'];assert.equal(R.earlyStart(b),true);b.isPlayer=true;assert.equal(R.earlyStart(b),false);near(R.startAllowance(b),.3);}
});
check('先駆移行は正規の旧 NPC だけ、一度だけ。判定・乱数・既存スキルは保持',()=>{const real=[{id:'cast_kagura',castId:'kagura',castRole:'boss'},{id:'cast_teiou',castId:'teiou',castRole:'king'},...['haruto','ren','izumi','sou','ibuki'].map(id=>({id:'main_'+id,racePersona:'rival_final'}))];for(const q of real){const b={...q,isPlayer:false,stats:{start:70},skills:['quick'],startTime:-.1,startFault:null,seed:123};assert.equal(R.migrateStartSkills(b),true);assert.deepEqual(b.skills,['quick','pioneer_start']);assert.equal(R.migrateStartSkills(b),false);assert.equal(b.startTime,-.1);assert.equal(b.startFault,null);assert.equal(b.seed,123);}
 for(const q of [{id:'cast_kagura',castRole:'boss'},{id:'cast_kagura',castId:'kagura',castRole:'mentor'},{id:'cast_teiou',castRole:'king'},{id:'other',racePersona:'rival_final'},{id:'main_izumi',racePersona:'rival_ally'},{id:'main_izumi',racePersona:'rival_final',castRole:'mentor'},...real.map(q=>({...q,isPlayer:true}))]){const b={...q,skills:[]};assert.equal(R.migrateStartSkills(b),false,JSON.stringify(q));assert.deepEqual(b.skills,[]);}
});
check('先駆を新規生成の ID だけで再付与しない',()=>{const {r}=fixture();Object.assign(r.runners[1],{id:'cast_kagura',castId:'kagura',castRole:'boss',stats:{speed:50,turn:50,start:70,accel:50,power:50},skills:[]});const d=R.create(r,124);assert.equal(R.earlyStart(d.boats[1]),false);assert.equal(R.startAllowance(d.boats[1]),0);});
check('旧途中の未通過目標は更新し、通過済みの ST / F は遡及変更しない',()=>{const {r,d,b}=fixture();d.paused=false;d.elapsed=1;d.frame=60;b.stats.start=70;b.startAim=-.2;const passed=d.boats.find(n=>n!==b);passed.startTime=-.1;passed.startFault=null;passed.startAim=-.18;const fault=d.boats.find(n=>n!==b&&n!==passed);fault.startTime=-.4;fault.startFault='F';fault.dnf=true;for(const n of d.boats)n.lastZone='0:0';const seed=d.seed;R.tick(d,r,{throttle:0});assert.ok(b.startAim>0);assert.equal(passed.startTime,-.1);assert.equal(passed.startFault,null);assert.equal(passed.startAim,-.18);assert.equal(fault.startFault,'F');assert.equal(d.seed,seed);});
for(const policy of ['safe','attack'])check('通常 B 以下の実助走で全 6 コースが合法通過: '+policy,()=>{for(const [stat,wind,windSpeed] of [[0,'無風',0],[65,'向かい風',10],[70,'追い風',10],[79.999,'横風',10],[80,'無風',0],[100,'無風',0]]){const {r,d}=fixture(100+Math.floor(stat));r.startPolicy=policy;r.env.wind=wind;r.env.windSpeed=windSpeed;for(const n of d.boats)n.stats.start=stat;d.paused=false;while(d.elapsed<13.49)R.tick(d,r,{},R.DT,true);for(const n of d.boats){assert.equal(n.startFault,null,`${policy}/${stat}/${n.course}`);assert.ok(n.startTime!==null);assert.ok(n.startTime>=-R.startAllowance(n)-1e-7);if(stat<80)assert.ok(n.startTime>=0);}report.startRuns.push({policy,start:stat,wind,ST:d.boats.map(n=>+n.startTime.toFixed(6))});}});
check('先駆の実助走は所持時だけ。A 未満でも先駆、通常特能は通常助走',()=>{for(const [stat,skills] of [[20,['pioneer_start']],[70,['pioneer_start']],[100,['pioneer_start']],[70,[]],[70,['zero']],[70,['legend_start']]]){const {r,d}=fixture();const b=d.boats[1];b.stats.start=stat;b.skills=skills;d.paused=false;while(d.elapsed<13.49)R.tick(d,r,{},R.DT,true);assert.equal(b.startFault,null);assert.ok(b.startTime!==null);if(skills.includes('pioneer_start'))near(b.startTime,-.3,.0001);else assert.ok(b.startTime>=-R.startAllowance(b));report.startRuns.push({start:stat,skills,ST:b.startTime});}});
check('実 V124 の助走途中セーブを復元し、A 未満目標へ更新。育成能力を維持',()=>{const raw=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures/start-v124-save.json'),'utf8')),s=E.decode(JSON.stringify(raw));assert.ok(E.validState(s));assert.deepEqual(s.career.player.stats,raw.career.player.stats);const r=s.career.series.race,d=r.drive,own=R.own(d);assert.equal(own.stats.start,70);assert.equal(R.startAllowance(own),0);const a=clone(d),b=clone(d);for(const n of a.boats)if(n.startTime===null)n.startAim=-.3;for(const n of b.boats)if(n.startTime===null)n.startAim=.2;a.paused=b.paused=false;for(let i=0;i<600;i++){R.tick(a,r,{},R.DT,true);R.tick(b,r,{},R.DT,true);}assert.deepEqual(a,b);assert.ok(a.boats.every(n=>!n.startFault));assert.ok(R.valid(a,r));});
check('練習は revision 3。V123/C と V124/B の合法早発記録は保持して比較を分離',()=>{let store=P.sanitize(null);for(const file of ['practice-v123.json','practice-v124.json']){const old=JSON.parse(fs.readFileSync(path.join(__dirname,'fixtures',file),'utf8'));const clean=P.sanitize(old.store);assert.deepEqual(clean,old.store);const prior=clone(old.store);const z=P.record(clean,old.trial);assert.equal(z.comparison.first,true);assert.equal(z.comparison.current.status,'F');assert.equal(z.comparison.best,null);assert.equal(z.store.groups.length,2);assert.deepEqual(z.store.groups[0],prior.groups[0]);assert.equal(JSON.parse(z.store.groups[1].key.slice(5)).revision,3);report.oldRecords.push({file,revision:JSON.parse(prior.groups[0].key.slice(5)).revision,best:prior.groups[0].best.st,preserved:true});store.groups.push(...clean.groups);}assert.equal(P.sanitize(store).groups.length,2);});
check('現行練習の 0 秒は合法、B 早発は F、所持例外の範囲内だけベスト対象',()=>{for(const [skills,st,status] of [[[],0,'complete'],[[],-.001,'F'],[['zero'],-.06,'complete'],[['zero'],-.061,'F'],[['legend_start'],-.1,'complete']]){const t=Craft.practice(E,'start',undefined,125),b=R.own(t.r.drive);b.stats.start=70;b.skills=skills;t.initial=clone(t.r);t.r.drive.finished=true;t.r.drive.elapsed+=15;b.progress=t.r.practiceLimit;b.startTime=st;b.startFault=null;b.dnf=false;b.capsized=false;const z=P.record(null,t);assert.equal(z.comparison.current.status,status);assert.equal(z.comparison.best?.st??null,status==='complete'?st:null);assert.deepEqual(P.sanitize(z.store),z.store);}});
report.passed=report.checks.length;fs.writeFileSync(path.join(__dirname,'start-v125.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.passed,startRuns:report.startRuns.length,oldRecords:report.oldRecords.length}));
