const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const E=require('../src/script'),D=E.Drama.B,B=E.Bonds.B,oldRoot=path.join(__dirname,fs.existsSync(path.join(__dirname,'../work119/original-src'))?'../work119/original-src':'../v118-backup/src');
const O=require(path.join(oldRoot,'drama-data')),P=require(path.join(oldRoot,'bonds-data'));
const report={checks:[],routes:[],volume:{}};function test(name,f){f();report.checks.push(name);}
const count=x=>x.reduce((n,t)=>n+Array.from(t).length,0),main=x=>Object.values(x.arcs).flatMap(a=>[...a.intro,...a.chapters.flatMap(c=>c[1])]),hero=x=>x.heroines.flatMap(h=>[...h.chapters.flatMap(c=>c.body),...h.final,...(h.recoveryChapters||[]).flatMap(c=>c.body),...(h.recoveryFinal||[])]);
report.volume={main:{before:count(main(O)),after:count(main(D))},heroines:{before:count(hero(P)),after:count(hero(B))},visits:{scenes:B.heroines.reduce((n,h)=>n+h.visits.length,0),characters:count(B.heroines.flatMap(h=>h.visits.flat()))}};
for(const [id,a] of Object.entries(D.arcs))test('概要と全10場面の増量 '+id,()=>{assert.equal(a.chapters.length,9);for(const [k,v] of Object.entries(a.overview))assert.ok(typeof v==='string'&&v.length>(k==='genre'?3:8));const now=[a.intro,...a.chapters.map(c=>c[1])],before=[O.arcs[id].intro,...O.arcs[id].chapters.map(c=>c[1])];now.forEach((body,i)=>{assert.ok(count(body)>count(before[i])*1.3,id+':'+i);assert.ok(body.length<80);assert.equal(body.length,new Set(body).size);assert.ok(body.every(s=>s.length<3000));});});
test('本編選択・報酬・結果分岐の数値条件を維持',()=>{for(const key of Object.keys(O))if(key!=='arcs')assert.deepEqual(D[key],O[key]);});
for(const h of B.heroines)test('7話の条件・選択と再起専用の構造を維持 '+h.id,()=>{const before=P.map[h.id];for(const k of ['chapters','recoveryChapters'])if(h[k]){assert.equal(h[k].length,7);h[k].forEach((ch,i)=>{const {body,...meta}=ch,{body:oldBody,...oldMeta}=before[k][i];assert.deepEqual(meta,oldMeta);assert.ok(count(body)>count(oldBody)*1.3);assert.equal(body.length,new Set(body).size);assert.ok(body.length<100);});}assert.ok(count(h.final)>count(before.final));assert.equal(h.skill,before.skill);assert.equal(h.visits.length,2);assert.notDeepEqual(h.visits[0],h.visits[1]);});
test('レース物理・強敵報酬・日常能力獲得・攻略ゲートはソース不変',()=>{for(const n of ['racing','cast','story','finale','craft118','affinity'])assert.equal(fs.readFileSync(path.join(__dirname,'../src/'+n+'.js'),'utf8'),fs.readFileSync(path.join(oldRoot,n+'.js'),'utf8'));});
test('選んだ4ルートをそのまま開始し、ランダムで4本に到達',()=>{const found=new Set();for(let seed=1;seed<=64;seed++){const s=E.newState(seed),p=E.character(s,'選択検証');p.scenario='random';const c=E.createCareer(s,p);found.add(c.campaign.arc);assert.equal(c.player.scenario,c.campaign.arc);assert.ok(E.validState(s));}assert.deepEqual([...found].sort(),Object.keys(D.arcs).sort());for(const id of Object.keys(D.arcs)){const s=E.newState(9),p=E.character(s,'指定検証');p.scenario=id;assert.equal(E.createCareer(s,p).campaign.arc,id);}});
for(const arc of ['light','recovery'])for(const h of B.heroines)test('G1優勝まで終盤は開かず、全7話の完走経路が存続 '+arc+'/'+h.id,()=>{const s=E.newState(19),p=E.character(s,'関係検証');p.scenario=arc;const c=E.createCareer(s,p),q=c.bonds.heroines[h.id];Object.assign(q,{met:true,metStage:2,metRace:12});let blocked=false;for(let n=12;n<=53;n++){c.stats.races=n;c.stage=Math.min(8,Math.floor(n/6));c.status='home';if(n===42)c.history.push({stage:6,champion:true});const offer=E.Affinity.offer(c);if(offer)E.Affinity.reply(c,offer.id,1,E);const g=E.Bonds.gate(c,h.id);if(q.step===5&&n<42&&!g.chapter)blocked=true;if(!g.open)continue;const pending=E.Bonds.open(c,h.id),before=JSON.stringify(c),sc=E.Bonds.scene(c);assert.equal(JSON.stringify(c),before);assert.deepEqual(E.Bonds.scene(c),sc);if(sc.kind==='chapter')assert.deepEqual(sc.body,(arc==='recovery'&&h.recoveryChapters?h.recoveryChapters:h.chapters)[q.step].body);const best=sc.choices.map((x,i)=>({x,i})).filter(({x})=>!x.break&&!x.friend).sort((a,b)=>((b.x.trust||0)+(b.x.affection||0))-((a.x.trust||0)+(a.x.affection||0)))[0];assert.ok(E.Bonds.choose(c,pending.key,best.i));if(q.step===7)break;}assert.ok(blocked);assert.equal(q.step,7);assert.equal(c.bonds.completed,h.id);assert.ok(E.Bonds.valid(c.bonds));report.routes.push({arc,id:h.id,completedAt:c.stats.races,blockedBeforeG1:blocked});});
test('V118の能力・機材・選択・凍結済み本文・走行を維持して移行',()=>{const ctx=vm.createContext({});for(const n of JSON.parse(fs.readFileSync(path.join(__dirname,fs.existsSync(path.join(__dirname,'../work119/original-script-order.json'))?'../work119/original-script-order.json':'../v118-backup/tools/script_order.json')))){if(['portrait-assets','audio-assets','music','visual-assets'].includes(n))continue;vm.runInContext(fs.readFileSync(path.join(oldRoot,n+'.js'),'utf8'),ctx);}const raw=vm.runInContext(`const E=KM_ENGINE,s=E.newState(118),p=E.character(s,'前版の選手');p.scenario='recovery';const c=E.createCareer(s,p);E.Drama.choose(c,'opening',0,E);E.startSeries(s);E.prepareRace(s);E.startDrive(c,c.series.race);JSON.stringify(s);`,ctx),before=JSON.parse(raw),after=E.decode(raw);assert.equal(after.build,'119');for(const key of ['player','campaign'])assert.deepEqual(after.career[key],before.career[key]);assert.deepEqual(after.career.series.race.drive,before.career.series.race.drive);assert.ok(E.validState(after));assert.deepEqual(E.Campaign.scene(after.career.campaign,'opening').body,JSON.parse(vm.runInContext("JSON.stringify(KM_ENGINE.Campaign.scene(s.career.campaign,'opening').body)",ctx)));fs.writeFileSync(path.join(__dirname,'v118-save.json'),raw);});
report.total=report.checks.length;fs.writeFileSync(path.join(__dirname,'story-v119.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
