const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),vm=require('vm');
const E=require('../src/script'),R=E.R,clone=structuredClone;
const report={checks:[],starts:[],practices:[],profiles:[]};let checks=0;
function test(name,fn){fn();report.checks.push(name);checks++;}
function career(arc='recovery',seed=118){const s=E.newState(seed),p=E.character(s,'検証選手');p.scenario=arc;const c=E.createCareer(s,p);return{s,c};}
function race(arc='recovery',seed=118){const {s,c}=career(arc,seed);E.startSeries(s);E.prepareRace(s);return{s,c,r:c.series.race};}
function met(c,id='nagi',step=5){Object.assign(c.bonds.heroines[id],{met:true,metStage:2,metRace:12,step,trust:100,affection:100,choices:Array(step).fill(0)});c.stats.races=46;c.stage=7;c.status='home';c.bonds.nextAt=0;c.affinity.requests=[];return c.bonds.heroines[id];}
function champion(stage=6){return{stage,champion:true,qualificationRank:1,finalPlace:1,finalType:'championship'};}
test('第6話は今育成のG1優勝が必須。高い好感度やG2優勝では解除しない',()=>{const{c}=career();met(c);assert.equal(E.Bonds.gate(c,'nagi').chapter,false);c.history=[champion(5)];assert.equal(E.Bonds.gate(c,'nagi').chapter,false);c.history=[{...champion(6),champion:false}];assert.equal(E.Bonds.gate(c,'nagi').chapter,false);for(const stage of [6,7]){c.history=[champion(stage)];assert.equal(E.Bonds.gate(c,'nagi').chapter,true);}});
test('G1優勝だけでは好感度・信頼条件を飛び越えない',()=>{const{c}=career();const h=met(c);c.history=[champion()];h.affection=0;assert.equal(E.Bonds.gate(c,'nagi').chapter,false);h.affection=100;h.trust=0;assert.equal(E.Bonds.gate(c,'nagi').chapter,false);});
test('出会いの抽選は据え置き・遅い出会いも完走保証しない',()=>{assert.deepEqual(E.Bonds.encounterRates,[.004,.009,.020,.029,.042,.050,.060,.073,.090]);const{c}=career();const h=met(c,'nagi',0);h.metStage=8;c.stage=8;c.series={round:4};assert.match(E.Bonds.outlook(c,'nagi'),/届かない/);assert.equal(E.Craft.waitLength(c,'nagi',1),1);assert.equal(E.Craft.waitLength(c,'nagi',6),2);});
test('未完走の結びは記録だけで能力・交際を付与しない',()=>{const{c}=career();met(c);c.ending='sgFinished';const before=JSON.stringify(c);const q=E.Craft.epilogue(c);assert.equal(q.length,1);assert.equal(JSON.stringify(c),before);});
test('移行時に第6話を開いていた人物は進行を維持',()=>{const{c}=career();met(c);delete c.refinement;c.bonds.pending={id:'nagi',step:5,kind:'chapter'};E.Craft.ensure(c);assert.ok(c.refinement.grandfather.includes('nagi'));assert.equal(E.Craft.romanceGate(c,'nagi'),true);});
test('恋愛完走のLRはSG優勝戦前のみ、一度だけ',()=>{const{c}=career();const h=met(c,'nagi',7);h.dated=true;c.bonds.partner=c.bonds.completed='nagi';c.stage=8;c.history=[champion()];const r={id:'sg_final',type:'championship',done:false};c.series={race:r};const before=c.player.skills.length;assert.ok(E.Bonds.final(c,r,E));assert.equal(c.player.skills.length,before+1);assert.equal(E.Bonds.final(c,r,E),null);assert.equal(c.bonds.reward.skill,E.Bonds.B.map.nagi.skill);const{c:d}=career();const hh=met(d,'nagi',7);hh.dated=true;d.bonds.partner=d.bonds.completed='nagi';d.stage=8;d.series={race:r};assert.equal(E.Bonds.final(d,r,E),null);});
function request(c,type='gift'){const h=c.bonds.heroines.nagi;Object.assign(h,{met:true,metStage:0,metRace:0,step:1,choices:[0],affection:30});const q={id:'nagi:1',heroine:'nagi',chapter:1,type,cost:type==='gift'?90:0,target:type==='race'?3:0,status:'offer',created:c.stats.races,deadline:null,resolved:null,delta:null};c.affinity.requests=[q];c.affinity.rolled=[q.id];return q;}
test('協力は練習1回と交換・賞金不変・二重取得なし',()=>{const{c}=race();const q=request(c),a=c.series.action;const before=a.normal+a.training,money=c.player.money;assert.ok(E.Affinity.reply(c,q.id,2,E));assert.equal(a.normal+a.training,before-1);assert.equal(c.player.money,money);assert.equal(c.bonds.heroines.nagi.affection,36);assert.equal(q.support,true);assert.equal(E.Affinity.reply(c,q.id,2,E),null);assert.ok(E.Affinity.valid(c.affinity));});
test('贈り物を断っても好感度は下げず、無料の協力はできない',()=>{const{c}=race();let q=request(c);c.series.action.normal=c.series.action.training=0;assert.equal(E.Affinity.reply(c,q.id,2,E),null);assert.ok(E.Affinity.reply(c,q.id,1,E));assert.equal(c.bonds.heroines.nagi.affection,30);q=request(c,'race');assert.equal(E.Affinity.reply(c,q.id,2,E),null);});
test('イベントの能力伝授は1シリーズ1回。ログ削除・再読込で復活しない',()=>{const{s,c,r}=race();let i=0;function event(){c.story.pending={kind:'event',key:'secret:'+i++,id:'secretwave',raceId:r.id,variant:0};return E.Story.choose(c,c.story.pending.key,0,E);}const first=event();assert.ok(first.skill);const next=event();assert.equal(next.skill,null);c.story.log=[];assert.equal(event().skill,null);assert.ok(E.Story.valid(c.story));const loaded=E.decode(JSON.stringify(s));assert.ok(loaded);assert.deepEqual(loaded.career.story.skillStages,[0]);c.stage=1;assert.ok(event().skill);});
test('V117の返答待ちイベントにも伝授上限を移行して適用',()=>{const{s,c,r}=race();delete c.story.skillStages;c.story.pending={kind:'event',key:'old_pending',id:'secretwave',raceId:r.id,variant:0};const loaded=E.decode(JSON.stringify(s));assert.ok(E.Story.choose(loaded.career,'old_pending',0,E));assert.deepEqual(loaded.career.story.skillStages,[0]);assert.ok(E.validState(loaded));});
for(const arc of Object.keys(E.Drama.B.arcs))for(const choice of [0,1])test('本編の両方の選択を成長につなげる '+arc+' '+choice,()=>{const{c}=career(arc);const decide=()=>{for(const e of E.Drama.pending(c.campaign)){const z=E.Drama.choose(c,e.id,choice,E);assert.ok(z);assert.equal(e.decision.key,E.Drama.B.paths118[arc][e.choiceSpec][2+choice]);assert.ok(e.decision.aligned);assert.equal(E.Drama.choose(c,e.id,choice,E),null);}};decide();for(let stage=0;stage<9;stage++){c.stage=stage;c.stats.races=(stage+1)*6;c.stats.wins=stage+1;const z=champion(stage);c.history.push(z);if(stage===8){Object.assign(c.development.paths.turn,{hints:5,practice:5,learned:true,branch:0});}E.Campaign.capture(c,z);decide();assert.ok(E.Campaign.valid(c.campaign),arc+' '+stage);}assert.ok(c.player.skills.includes(E.Drama.B.rewardSkills[arc]));const before=JSON.stringify(c.player);for(const e of c.campaign.entries)E.Campaign.scene(c.campaign,e.id);assert.equal(JSON.stringify(c.player),before);});
for(const mode of ['noG1','noBloom'])test('本編最終の自動配布を抑える '+mode,()=>{const{c}=career();for(let stage=-1;stage<9;stage++){if(stage>=0){c.stage=stage;c.stats.races=stage*6;const z=champion(stage);if(mode==='noBloom')c.history.push(z);if(mode==='noG1')Object.assign(c.development.paths.turn,{hints:5,practice:5,learned:true,branch:0});E.Campaign.capture(c,z);}for(const e of E.Drama.pending(c.campaign))E.Drama.choose(c,e.id,0,E);}assert.equal(c.campaign.entries.at(-1).decision.skill,null);});
test('本編へ実レースの反応を固定して保存',()=>{const{c}=career();c.refinement.races.push({id:'contact-race',stage:0,place:2,fault:null,capsized:false,dnf:false,contacts:2,review:null});E.Campaign.capture(c,{...champion(0),champion:false,finalPlace:2});const a=E.Campaign.scene(c.campaign,'season:0');assert.match(a.body.join(''),/他艇との接触が記録/);c.refinement.races[0].contacts=0;assert.deepEqual(E.Campaign.scene(c.campaign,'season:0'),a);assert.ok(E.Campaign.valid(c.campaign));});
test('技の実践は走った姿勢と区間を使用。失格には加算しない',()=>{const b={finishTime:100,startTime:-.1,metrics:{boundaries:0,rescues:0,craft:{straightGood:8,turnGood:5,exitGood:2,stableWater:6}}};for(const k of E.D.statKeys)assert.ok(E.Development.taskMet(k,b,{}));for(const k of ['speed','turn','accel','power'])assert.equal(E.Development.taskMet(k,{...b,metrics:{boundaries:0,rescues:0}},{}),false);b.startFault='F';for(const k of E.D.statKeys)assert.equal(E.Development.taskMet(k,b,{}),false);});
test('再起の方針はG2から固定し3走でコツのみ獲得',()=>{const{c}=career();assert.equal(E.Craft.recoveryPath(c,'renew'),false);c.stage=4;assert.ok(E.Craft.recoveryPath(c,'renew'));assert.equal(E.Craft.recoveryPath(c,'restore'),false);const key=E.Craft.recoveryKey(c.refinement.recovery),skills=clone(c.player.skills);for(let i=0;i<4;i++){const z={place:1,development:[{key,met:true}],driving:null};E.Craft.settle(c,{id:'rebuild'+i},z,E);}assert.equal(c.refinement.recovery.practice,3);assert.equal(c.development.paths[key].hints,.75);assert.deepEqual(c.player.skills,skills);assert.ok(E.Craft.valid(c.refinement));});
for(const kind of ['start','turn','wake'])test('練習条件の独立性 '+kind,()=>{const{s,c}=career();const before=JSON.stringify(s),t=E.Craft.practice(E,kind,c.player),r=t.r,d=r.drive;d.paused=false;for(let n=0;n<15000&&!d.finished;n++){R.tick(d,r,{},R.DT,true);const b=R.own(d);if(b.startFault||b.capsized||b.dnf||b.progress>=r.practiceLimit||R.raceTime(d)>(kind==='start'?12:65)){d.finished=true;d.paused=true;}}assert.equal(JSON.stringify(s),before);assert.ok(d.finished);assert.ok(E.Craft.analysis(d));report.practices.push({kind,time:R.raceTime(d),progress:R.own(d).progress,fault:R.own(d).startFault,contacts:R.own(d).metrics.contacts});});
for(const policy of ['safe','attack'])for(const stat of [30,60,100])for(const wind of ['無風','向かい風','追い風','横風'])test('発進方針の実走 '+policy+' '+stat+' '+wind,()=>{const{r}=race();r.startPolicy=policy;r.env={weather:'雨',wind,windSpeed:wind==='無風'?0:10};for(const n of r.runners)n.skills=[];const n=r.runners.find(n=>n.isPlayer);n.stats.start=stat;const d=R.create(r,118);d.paused=false;while(d.elapsed<14&&!R.own(d).startFault)R.tick(d,r,{},R.DT,true);const b=R.own(d);assert.equal(b.startFault,null);assert.ok(b.startTime!==null);report.starts.push({policy,stat,wind,st:b.startTime,allowance:R.startAllowance(b)});});
for(const key of E.D.statKeys)test('能力特化の実走・保存・区間記録 '+key,()=>{const{s,c,r}=race('light',155);for(const k of E.D.statKeys)c.player.stats[k]=k===key?90:55;E.syncPlayerSnapshot(c);c.status='preRace';E.autoResolve(s);const d=r.drive,b=R.own(d);assert.ok(E.validState(s),'settled '+key);assert.ok(E.decode(JSON.stringify(s)));assert.ok(b.metrics.craft.sectors.length>0);const z=c.lastResult;assert.ok(z.observation.sections.length>0);report.profiles.push({key,place:z.place,time:b.finishTime,contacts:b.metrics.contacts,technique:b.metrics.craft&&Object.fromEntries(['straightGood','turnGood','exitGood','stableWater'].map(k=>[k,b.metrics.craft[k]]))});});
test('V117の途中セーブを移行して既存能力・機材・既読を維持',()=>{const context=vm.createContext({});for(const n of JSON.parse(fs.readFileSync(fs.existsSync(path.join(__dirname,'../v117-backup/script_order.json'))?path.join(__dirname,'../v117-backup/script_order.json'):path.join(__dirname,'../v117-backup/tools/script_order.json')))){if(['portrait-assets','audio-assets','music','visual-assets'].includes(n))continue;vm.runInContext(fs.readFileSync(path.join(__dirname,'../v117-backup/src/'+n+'.js'),'utf8'),context);}const raw=vm.runInContext(`const E=KM_ENGINE,s=E.newState(117),p=E.character(s,'旧選手');p.scenario='recovery';const c=E.createCareer(s,p);E.startSeries(s);E.prepareRace(s);E.startDrive(c,c.series.race);JSON.stringify(s);`,context),before=JSON.parse(raw),after=E.decode(raw);assert.equal(after.build,'118');assert.deepEqual(after.career.player,before.career.player);assert.deepEqual(after.career.campaign,before.career.campaign);assert.deepEqual(after.career.series.race.drive,before.career.series.race.drive);assert.ok(E.validState(after));fs.writeFileSync(path.join(__dirname,'v117-save.json'),raw);});
report.total=checks;fs.writeFileSync(path.join(__dirname,'verification-v118.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({passed:checks,practices:report.practices,profiles:report.profiles}));
