"""Original procedural PCM music/SFX, reproducible and free of third-party recordings."""
from pathlib import Path
import math, wave, io, base64, json, random
ROOT=Path(__file__).resolve().parent.parent
SRC=ROOT/'dist' if (ROOT/'dist').exists() else ROOT
SR=16000
def wav(samples):
    import struct
    out=io.BytesIO()
    with wave.open(out,'wb') as f:
        f.setnchannels(1);f.setsampwidth(2);f.setframerate(SR)
        f.writeframes(b''.join(struct.pack('<h',round(max(-.95,min(.95,x))*32767)) for x in samples))
    return out.getvalue()
def music(race):
    beat=.375 if race else .5
    notes=[64,67,71,74,71,67,69,67,62,66,69,74,72,69,67,66,60,64,67,72,71,67,64,67,62,66,69,71,69,66,62,66]
    a=[]
    for i in range(round(beat*len(notes)*SR)):
        t=i/SR;step=int(t/beat);u=t%beat;freq=440*2**((notes[step]-69)/12)
        env=min(1,u/.015)*max(0,1-u/beat)**1.7
        lead=(math.sin(2*math.pi*freq*t)+.2*math.sin(4*math.pi*freq*t))*.14*env
        bassfreq=440*2**(([40,38,36,38][step//8]-69)/12)
        bass=math.sin(2*math.pi*bassfreq*t)*.09*(1-u/beat)
        drum=math.sin(2*math.pi*(65*u+35*(1-math.exp(-u*25))))*math.exp(-u*32)*(.13 if race else .055)
        a.append(lead+bass+drum)
    return wav(a)
def effect(name):
    rng=random.Random(92);duration={'click':.08,'start':.6,'skill':.6,'contact':.2,'finish':1.1,'engine':1}[name];a=[]
    for i in range(int(duration*SR)):
        t=i/SR;u=t/duration
        if name=='engine':v=.08*(math.sin(2*math.pi*80*t)+.45*math.sin(2*math.pi*160*t)+.18*math.sin(2*math.pi*240*t))
        elif name=='contact':v=(rng.random()*2-1)*.3*(1-u)**3
        else:
            f={'click':650,'start':880,'skill':440+880*u,'finish':[523,659,784,1047][min(3,int(u*4))]}[name]
            v=math.sin(2*math.pi*f*t)*.20*min(1,t/.006)*min(1,(duration-t)/.03)
        a.append(v)
    return wav(a)
assets={'harbor':music(False),'race':music(True),**{k:effect(k) for k in ['click','start','skill','contact','finish','engine']}}
(SRC/'audio-assets.js').write_text('/* Original PCM WAV assets generated by tools/make_audio.py. */\n(function(r){r.KM_AUDIO_ASSETS='+json.dumps({k:'data:audio/wav;base64,'+base64.b64encode(v).decode() for k,v in assets.items()})+';})(globalThis);\n')
print('Generated',len(assets),'original WAV assets:',sum(map(len,assets.values())),'bytes')
