


/* Original PCM WAV assets generated by tools/make_audio.py. */
(function(r){r.KM_AUDIO_ASSETS={"harbor": "assets/38981c4078befe9e5d09.wav", "race": "assets/2462937dd44f6df5e851.wav", "click": "assets/6b91f751e9a199980d0e.wav", "start": "assets/7542e5a9167449822396.wav", "skill": "assets/55044786e78554f6f380.wav", "contact": "assets/8e10cd8f737f1d879327.wav", "finish": "assets/70be312ce916a369825f.wav", "engine": "assets/ae24abf3e8ccb9ae72e9.wav"};})(globalThis);



